sm_name : acl_central_sm
includes: 
  - device_management/procedure_triggers.yaml
states:
  acl_central_sm_idle:
    START_PROCEDURE: acl_central_start_procedure_handler
  ACL_CENTRAL_TX_SCHEDULED: 
    TX_DONE: acl_central_tx_done_handler
    TX_ABORT: acl_central_tx_abort_handler
  ACL_CENTRAL_WAITING_FOR_RX_PKT_HEADER:
    RX_HEADER_RECEIVED: acl_central_header_received_done_handler
    RX_DONE: acl_central_rx_poll_null_done_handler
    RX_TIMEOUT: acl_central_header_received_timeout_handler
    RX_ABORT: acl_central_rx_abort_handler
  ACL_CENTRAL_WAITING_FOR_RX_COMPLETE: 
    RX_DONE: acl_central_rx_done_handler
    RX_ABORT: acl_central_rx_abort_handler
    RX_TIMEOUT: acl_central_rx_abort_handler
  