#ifndef LL_HCI_CMD_SET_DEF_COMPLETE_EVENT_H
#define LL_HCI_CMD_SET_DEF_COMPLETE_EVENT_H

/* Note - These macros are to be used while preparing a complete event packet only*/
/* Do not use these macros while preparing status event packet */
/* CE in the macro name stands for Complete Event*/
/* LINK_CONTROL RETURN_PARAMETERS */

#define SET_CE_INQUIRY_STATUS(buf,value)  buf[6] = value
#define INQUIRY_EVENT_PARAM_LENGTH 0 

#define SET_CE_INQUIRY_CANCEL_STATUS(buf,value)  buf[6] = value
//INQUIRY_CANCEL_status 1
#define INQUIRY_CANCEL_EVENT_PARAM_LENGTH 1 

#define SET_CE_PERIODIC_INQUIRY_MODE_STATUS(buf,value)  buf[6] = value
//PERIODIC_INQUIRY_MODE_status 1
#define PERIODIC_INQUIRY_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_EXIT_PERIODIC_INQUIRY_MODE_STATUS(buf,value)  buf[6] = value
//EXIT_PERIODIC_INQUIRY_MODE_status 1
#define EXIT_PERIODIC_INQUIRY_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_CREATE_CONNECTION_STATUS(buf,value)  buf[6] = value
#define CREATE_CONNECTION_EVENT_PARAM_LENGTH 0 

#define SET_CE_DISCONNECT_STATUS(buf,value)  buf[6] = value
#define DISCONNECT_EVENT_PARAM_LENGTH 0 

#define SET_CE_CREATE_CONNECTION_CANCEL_STATUS(buf,value)  buf[6] = value
//CREATE_CONNECTION_CANCEL_status 1
#define SET_CE_CREATE_CONNECTION_CANCEL_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//CREATE_CONNECTION_CANCEL_bd_addr 6
#define CREATE_CONNECTION_CANCEL_EVENT_PARAM_LENGTH 7 

#define SET_CE_ACCEPT_CONNECTION_REQUEST_STATUS(buf,value)  buf[6] = value
#define ACCEPT_CONNECTION_REQUEST_EVENT_PARAM_LENGTH 0 

#define SET_CE_REJECT_CONNECTION_REQUEST_STATUS(buf,value)  buf[6] = value
#define REJECT_CONNECTION_REQUEST_EVENT_PARAM_LENGTH 0 

#define SET_CE_LINK_KEY_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//LINK_KEY_REQUEST_REPLY_status 1
#define SET_CE_LINK_KEY_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//LINK_KEY_REQUEST_REPLY_bd_addr 6
#define LINK_KEY_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_LINK_KEY_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//LINK_KEY_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_LINK_KEY_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//LINK_KEY_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define LINK_KEY_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_PIN_CODE_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//PIN_CODE_REQUEST_REPLY_status 1
#define SET_CE_PIN_CODE_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//PIN_CODE_REQUEST_REPLY_bd_addr 6
#define PIN_CODE_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_PIN_CODE_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//PIN_CODE_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_PIN_CODE_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//PIN_CODE_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define PIN_CODE_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_CHANGE_CONNECTION_PACKET_TYPE_STATUS(buf,value)  buf[6] = value
#define CHANGE_CONNECTION_PACKET_TYPE_EVENT_PARAM_LENGTH 0 

#define SET_CE_AUTHENTICATION_REQUESTED_STATUS(buf,value)  buf[6] = value
#define AUTHENTICATION_REQUESTED_EVENT_PARAM_LENGTH 0 

#define SET_CE_SET_CONNECTION_ENCRYPTION_STATUS(buf,value)  buf[6] = value
#define SET_CONNECTION_ENCRYPTION_EVENT_PARAM_LENGTH 0 

#define SET_CE_CHANGE_CONNECTION_LINK_KEY_STATUS(buf,value)  buf[6] = value
#define CHANGE_CONNECTION_LINK_KEY_EVENT_PARAM_LENGTH 0 

#define SET_CE_REMOTE_NAME_REQUEST_STATUS(buf,value)  buf[6] = value
#define REMOTE_NAME_REQUEST_EVENT_PARAM_LENGTH 0 

#define SET_CE_REMOTE_NAME_REQUEST_CANCEL_STATUS(buf,value)  buf[6] = value
//REMOTE_NAME_REQUEST_CANCEL_status 1
#define SET_CE_REMOTE_NAME_REQUEST_CANCEL_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//REMOTE_NAME_REQUEST_CANCEL_bd_addr 6
#define REMOTE_NAME_REQUEST_CANCEL_EVENT_PARAM_LENGTH 7 

#define SET_CE_READ_REMOTE_SUPPORTED_FEATURES_STATUS(buf,value)  buf[6] = value
#define READ_REMOTE_SUPPORTED_FEATURES_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_REMOTE_EXTENDED_FEATURES_STATUS(buf,value)  buf[6] = value
#define READ_REMOTE_EXTENDED_FEATURES_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_REMOTE_VERSION_INFORMATION_STATUS(buf,value)  buf[6] = value
#define READ_REMOTE_VERSION_INFORMATION_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_CLOCK_OFFSET_STATUS(buf,value)  buf[6] = value
#define READ_CLOCK_OFFSET_EVENT_PARAM_LENGTH 0 

#define SET_CE_SETUP_SYNCHRONOUS_CONNECTION_STATUS(buf,value)  buf[6] = value
#define SETUP_SYNCHRONOUS_CONNECTION_EVENT_PARAM_LENGTH 0 

#define SET_CE_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_STATUS(buf,value)  buf[6] = value
#define ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_EVENT_PARAM_LENGTH 0 

#define SET_CE_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_STATUS(buf,value)  buf[6] = value
#define REJECT_SYNCHRONOUS_CONNECTION_REQUEST_EVENT_PARAM_LENGTH 0 

#define SET_CE_IO_CAPABILITY_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//IO_CAPABILITY_REQUEST_REPLY_status 1
#define SET_CE_IO_CAPABILITY_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//IO_CAPABILITY_REQUEST_REPLY_bd_addr 6
#define IO_CAPABILITY_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_USER_CONFIRMATION_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//USER_CONFIRMATION_REQUEST_REPLY_status 1
#define SET_CE_USER_CONFIRMATION_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//USER_CONFIRMATION_REQUEST_REPLY_bd_addr 6
#define USER_CONFIRMATION_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_USER_PASSKEY_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//USER_PASSKEY_REQUEST_REPLY_status 1
#define SET_CE_USER_PASSKEY_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//USER_PASSKEY_REQUEST_REPLY_bd_addr 6
#define USER_PASSKEY_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//USER_PASSKEY_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//USER_PASSKEY_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define USER_PASSKEY_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_REMOTE_OOB_DATA_REQUEST_REPLY_STATUS(buf,value)  buf[6] = value
//REMOTE_OOB_DATA_REQUEST_REPLY_status 1
#define SET_CE_REMOTE_OOB_DATA_REQUEST_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//REMOTE_OOB_DATA_REQUEST_REPLY_bd_addr 6
#define REMOTE_OOB_DATA_REQUEST_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 

#define SET_CE_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_STATUS(buf,value)  buf[6] = value
//IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_status 1
#define SET_CE_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_bd_addr 6
#define IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_EVENT_PARAM_LENGTH 7 


/* LINK_POLICY RETURN_PARAMETERS */

#define SET_CE_SNIFF_MODE_STATUS(buf,value)  buf[6] = value
#define SNIFF_MODE_EVENT_PARAM_LENGTH 0 

#define SET_CE_EXIT_SNIFF_MODE_STATUS(buf,value)  buf[6] = value
#define EXIT_SNIFF_MODE_EVENT_PARAM_LENGTH 0 

#define SET_CE_QOS_SETUP_STATUS(buf,value)  buf[6] = value
#define QOS_SETUP_EVENT_PARAM_LENGTH 0 

#define SET_CE_ROLE_DISCOVERY_STATUS(buf,value)  buf[6] = value
//ROLE_DISCOVERY_status 1
#define SET_CE_ROLE_DISCOVERY_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//ROLE_DISCOVERY_connection_handle 2
#define SET_CE_ROLE_DISCOVERY_CURRENT_ROLE(buf,value)  buf[9] = value
//ROLE_DISCOVERY_current_role 1
#define ROLE_DISCOVERY_EVENT_PARAM_LENGTH 4 

#define SET_CE_SWITCH_ROLE_STATUS(buf,value)  buf[6] = value
#define SWITCH_ROLE_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_LINK_POLICY_SETTINGS_STATUS(buf,value)  buf[6] = value
//READ_LINK_POLICY_SETTINGS_status 1
#define SET_CE_READ_LINK_POLICY_SETTINGS_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_LINK_POLICY_SETTINGS_connection_handle 2
#define SET_CE_READ_LINK_POLICY_SETTINGS_LINK_POLICY_SETTINGS(buf,value)  *(uint16_t *)&buf[9] =value
//READ_LINK_POLICY_SETTINGS_link_policy_settings 2
#define READ_LINK_POLICY_SETTINGS_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_LINK_POLICY_SETTINGS_STATUS(buf,value)  buf[6] = value
//WRITE_LINK_POLICY_SETTINGS_status 1
#define SET_CE_WRITE_LINK_POLICY_SETTINGS_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//WRITE_LINK_POLICY_SETTINGS_connection_handle 2
#define WRITE_LINK_POLICY_SETTINGS_EVENT_PARAM_LENGTH 3 

#define SET_CE_READ_DEFAULT_LINK_POLICY_SETTINGS_STATUS(buf,value)  buf[6] = value
//READ_DEFAULT_LINK_POLICY_SETTINGS_status 1
#define SET_CE_READ_DEFAULT_LINK_POLICY_SETTINGS_DEFAULT_LINK_POLICY_SETTINGS(buf,value)  *(uint16_t *)&buf[7] =value
//READ_DEFAULT_LINK_POLICY_SETTINGS_default_link_policy_settings 2
#define READ_DEFAULT_LINK_POLICY_SETTINGS_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_DEFAULT_LINK_POLICY_SETTINGS_STATUS(buf,value)  buf[6] = value
//WRITE_DEFAULT_LINK_POLICY_SETTINGS_status 1
#define WRITE_DEFAULT_LINK_POLICY_SETTINGS_EVENT_PARAM_LENGTH 1 

#define SET_CE_SNIFF_SUBRATING_STATUS(buf,value)  buf[6] = value
//SNIFF_SUBRATING_status 1
#define SET_CE_SNIFF_SUBRATING_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//SNIFF_SUBRATING_connection_handle 2
#define SNIFF_SUBRATING_EVENT_PARAM_LENGTH 3 


/* CONTROLLER_AND_BASEBAND RETURN_PARAMETERS */

#define SET_CE_SET_EVENT_MASK_STATUS(buf,value)  buf[6] = value
//SET_EVENT_MASK_status 1
#define SET_EVENT_MASK_EVENT_PARAM_LENGTH 1 

#define SET_CE_RESET_STATUS(buf,value)  buf[6] = value
//RESET_status 1
#define RESET_EVENT_PARAM_LENGTH 1 

#define SET_CE_SET_EVENT_FILTER_STATUS(buf,value)  buf[6] = value
//SET_EVENT_FILTER_status 1
#define SET_EVENT_FILTER_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_PIN_TYPE_STATUS(buf,value)  buf[6] = value
//READ_PIN_TYPE_status 1
#define SET_CE_READ_PIN_TYPE_PIN_TYPE(buf,value)  buf[7] = value
//READ_PIN_TYPE_pin_type 1
#define READ_PIN_TYPE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_PIN_TYPE_STATUS(buf,value)  buf[6] = value
//WRITE_PIN_TYPE_status 1
#define WRITE_PIN_TYPE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_STORED_LINK_KEY_STATUS(buf,value)  buf[6] = value
//READ_STORED_LINK_KEY_status 1
#define SET_CE_READ_STORED_LINK_KEY_MAX_NUM_KEYS(buf,value)  *(uint16_t *)&buf[7] =value
//READ_STORED_LINK_KEY_max_num_keys 2
#define SET_CE_READ_STORED_LINK_KEY_NUM_KEYS_READ(buf,value)  *(uint16_t *)&buf[9] =value
//READ_STORED_LINK_KEY_num_keys_read 2
#define READ_STORED_LINK_KEY_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_STORED_LINK_KEY_STATUS(buf,value)  buf[6] = value
//WRITE_STORED_LINK_KEY_status 1
#define SET_CE_WRITE_STORED_LINK_KEY_NUM_KEYS_WRITTEN(buf,value)  buf[7] = value
//WRITE_STORED_LINK_KEY_num_keys_written 1
#define WRITE_STORED_LINK_KEY_EVENT_PARAM_LENGTH 2 

#define SET_CE_DELETE_STORED_LINK_KEY_STATUS(buf,value)  buf[6] = value
//DELETE_STORED_LINK_KEY_status 1
#define SET_CE_DELETE_STORED_LINK_KEY_NUM_KEYS_DELETED(buf,value)  buf[7] = value
//DELETE_STORED_LINK_KEY_num_keys_deleted 1
#define DELETE_STORED_LINK_KEY_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_LOCAL_NAME_STATUS(buf,value)  buf[6] = value
//WRITE_LOCAL_NAME_status 1
#define WRITE_LOCAL_NAME_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_LOCAL_NAME_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_NAME_status 1
#define SET_CE_READ_LOCAL_NAME_LOCAL_NAME(buf,value)  memcpy((uint8_t *)&buf[7], &value, 248)
//READ_LOCAL_NAME_local_name 248
#define READ_LOCAL_NAME_EVENT_PARAM_LENGTH 249 

#define SET_CE_READ_CONNECTION_ACCEPT_TIMEOUT_STATUS(buf,value)  buf[6] = value
//READ_CONNECTION_ACCEPT_TIMEOUT_status 1
#define SET_CE_READ_CONNECTION_ACCEPT_TIMEOUT_CONNECTION_ACCEPT_TIMEOUT(buf,value)  *(uint16_t *)&buf[7] =value
//READ_CONNECTION_ACCEPT_TIMEOUT_connection_accept_timeout 2
#define READ_CONNECTION_ACCEPT_TIMEOUT_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_CONNECTION_ACCEPT_TIMEOUT_STATUS(buf,value)  buf[6] = value
//WRITE_CONNECTION_ACCEPT_TIMEOUT_status 1
#define WRITE_CONNECTION_ACCEPT_TIMEOUT_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_PAGE_TIMEOUT_STATUS(buf,value)  buf[6] = value
//READ_PAGE_TIMEOUT_status 1
#define SET_CE_READ_PAGE_TIMEOUT_PAGE_TIMEOUT(buf,value)  *(uint16_t *)&buf[7] =value
//READ_PAGE_TIMEOUT_page_timeout 2
#define READ_PAGE_TIMEOUT_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_PAGE_TIMEOUT_STATUS(buf,value)  buf[6] = value
//WRITE_PAGE_TIMEOUT_status 1
#define WRITE_PAGE_TIMEOUT_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_SCAN_ENABLE_STATUS(buf,value)  buf[6] = value
//READ_SCAN_ENABLE_status 1
#define SET_CE_READ_SCAN_ENABLE_SCAN_ENABLE(buf,value)  buf[7] = value
//READ_SCAN_ENABLE_scan_enable 1
#define READ_SCAN_ENABLE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_SCAN_ENABLE_STATUS(buf,value)  buf[6] = value
//WRITE_SCAN_ENABLE_status 1
#define WRITE_SCAN_ENABLE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_PAGE_SCAN_ACTIVITY_STATUS(buf,value)  buf[6] = value
//READ_PAGE_SCAN_ACTIVITY_status 1
#define SET_CE_READ_PAGE_SCAN_ACTIVITY_PAGE_SCAN_INTERVAL(buf,value)  *(uint16_t *)&buf[7] =value
//READ_PAGE_SCAN_ACTIVITY_page_scan_interval 2
#define SET_CE_READ_PAGE_SCAN_ACTIVITY_PAGE_SCAN_WINDOW(buf,value)  *(uint16_t *)&buf[9] =value
//READ_PAGE_SCAN_ACTIVITY_page_scan_window 2
#define READ_PAGE_SCAN_ACTIVITY_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_PAGE_SCAN_ACTIVITY_STATUS(buf,value)  buf[6] = value
//WRITE_PAGE_SCAN_ACTIVITY_status 1
#define WRITE_PAGE_SCAN_ACTIVITY_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_INQUIRY_SCAN_ACTIVITY_STATUS(buf,value)  buf[6] = value
//READ_INQUIRY_SCAN_ACTIVITY_status 1
#define SET_CE_READ_INQUIRY_SCAN_ACTIVITY_INQUIRY_SCAN_INTERVAL(buf,value)  *(uint16_t *)&buf[7] =value
//READ_INQUIRY_SCAN_ACTIVITY_inquiry_scan_interval 2
#define SET_CE_READ_INQUIRY_SCAN_ACTIVITY_INQUIRY_SCAN_WINDOW(buf,value)  *(uint16_t *)&buf[9] =value
//READ_INQUIRY_SCAN_ACTIVITY_inquiry_scan_window 2
#define READ_INQUIRY_SCAN_ACTIVITY_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_INQUIRY_SCAN_ACTIVITY_STATUS(buf,value)  buf[6] = value
//WRITE_INQUIRY_SCAN_ACTIVITY_status 1
#define WRITE_INQUIRY_SCAN_ACTIVITY_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_AUTHENTICATION_ENABLE_STATUS(buf,value)  buf[6] = value
//READ_AUTHENTICATION_ENABLE_status 1
#define SET_CE_READ_AUTHENTICATION_ENABLE_AUTHENTICATION_ENABLE(buf,value)  buf[7] = value
//READ_AUTHENTICATION_ENABLE_authentication_enable 1
#define READ_AUTHENTICATION_ENABLE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_AUTHENTICATION_ENABLE_STATUS(buf,value)  buf[6] = value
//WRITE_AUTHENTICATION_ENABLE_status 1
#define WRITE_AUTHENTICATION_ENABLE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_CLASS_OF_DEVICE_STATUS(buf,value)  buf[6] = value
//READ_CLASS_OF_DEVICE_status 1
#define SET_CE_READ_CLASS_OF_DEVICE_CLASS_OF_DEVICE(buf,value)  *(uint32_t *)&buf[7] & 0xFFFFFF = value
//READ_CLASS_OF_DEVICE_class_of_device 3
#define READ_CLASS_OF_DEVICE_EVENT_PARAM_LENGTH 4 

#define SET_CE_WRITE_CLASS_OF_DEVICE_STATUS(buf,value)  buf[6] = value
//WRITE_CLASS_OF_DEVICE_status 1
#define WRITE_CLASS_OF_DEVICE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_VOICE_SETTING_STATUS(buf,value)  buf[6] = value
//READ_VOICE_SETTING_status 1
#define SET_CE_READ_VOICE_SETTING_VOICE_SETTING(buf,value)  *(uint16_t *)&buf[7] =value
//READ_VOICE_SETTING_voice_setting 2
#define READ_VOICE_SETTING_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_VOICE_SETTING_STATUS(buf,value)  buf[6] = value
//WRITE_VOICE_SETTING_status 1
#define WRITE_VOICE_SETTING_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_AUTOMATIC_FLUSH_TIMEOUT_STATUS(buf,value)  buf[6] = value
//READ_AUTOMATIC_FLUSH_TIMEOUT_status 1
#define SET_CE_READ_AUTOMATIC_FLUSH_TIMEOUT_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_AUTOMATIC_FLUSH_TIMEOUT_connection_handle 2
#define SET_CE_READ_AUTOMATIC_FLUSH_TIMEOUT_FLUSH_TIMEOUT(buf,value)  *(uint16_t *)&buf[9] =value
//READ_AUTOMATIC_FLUSH_TIMEOUT_flush_timeout 2
#define READ_AUTOMATIC_FLUSH_TIMEOUT_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_AUTOMATIC_FLUSH_TIMEOUT_STATUS(buf,value)  buf[6] = value
//WRITE_AUTOMATIC_FLUSH_TIMEOUT_status 1
#define SET_CE_WRITE_AUTOMATIC_FLUSH_TIMEOUT_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//WRITE_AUTOMATIC_FLUSH_TIMEOUT_connection_handle 2
#define WRITE_AUTOMATIC_FLUSH_TIMEOUT_EVENT_PARAM_LENGTH 3 

#define SET_CE_READ_TRANSMIT_POWER_LEVEL_STATUS(buf,value)  buf[6] = value
//READ_TRANSMIT_POWER_LEVEL_status 1
#define SET_CE_READ_TRANSMIT_POWER_LEVEL_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_TRANSMIT_POWER_LEVEL_connection_handle 2
#define SET_CE_READ_TRANSMIT_POWER_LEVEL_TX_POWER_LEVEL(buf,value)  buf[9] = value
//READ_TRANSMIT_POWER_LEVEL_tx_power_level 1
#define READ_TRANSMIT_POWER_LEVEL_EVENT_PARAM_LENGTH 4 

#define SET_CE_READ_LINK_SUPERVISION_TIMEOUT_STATUS(buf,value)  buf[6] = value
//READ_LINK_SUPERVISION_TIMEOUT_status 1
#define SET_CE_READ_LINK_SUPERVISION_TIMEOUT_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_LINK_SUPERVISION_TIMEOUT_handle 2
#define SET_CE_READ_LINK_SUPERVISION_TIMEOUT_LINK_SUPERVISION_TIMEOUT(buf,value)  *(uint16_t *)&buf[9] =value
//READ_LINK_SUPERVISION_TIMEOUT_link_supervision_timeout 2
#define READ_LINK_SUPERVISION_TIMEOUT_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_LINK_SUPERVISION_TIMEOUT_STATUS(buf,value)  buf[6] = value
//WRITE_LINK_SUPERVISION_TIMEOUT_status 1
#define SET_CE_WRITE_LINK_SUPERVISION_TIMEOUT_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//WRITE_LINK_SUPERVISION_TIMEOUT_handle 2
#define WRITE_LINK_SUPERVISION_TIMEOUT_EVENT_PARAM_LENGTH 3 

#define SET_CE_READ_NUMBER_OF_SUPPORTED_IAC_STATUS(buf,value)  buf[6] = value
//READ_NUMBER_OF_SUPPORTED_IAC_status 1
#define SET_CE_READ_NUMBER_OF_SUPPORTED_IAC_NUM_SUPPORTED_IAC(buf,value)  buf[7] = value
//READ_NUMBER_OF_SUPPORTED_IAC_num_supported_iac 1
#define READ_NUMBER_OF_SUPPORTED_IAC_EVENT_PARAM_LENGTH 2 

#define SET_CE_READ_CURRENT_IAC_LAP_STATUS(buf,value)  buf[6] = value
//READ_CURRENT_IAC_LAP_status 1
#define SET_CE_READ_CURRENT_IAC_LAP_NUM_CURRENT_IAC(buf,value)  buf[7] = value
//READ_CURRENT_IAC_LAP_num_current_iac 1
#define SET_CE_READ_CURRENT_IAC_LAP_IAC_LAP(buf,value)  *(uint32_t *)&buf[8] & 0xFFFFFF = value
//READ_CURRENT_IAC_LAP_iac_lap 3
#define READ_CURRENT_IAC_LAP_EVENT_PARAM_LENGTH 5 

#define SET_CE_WRITE_CURRENT_IAC_LAP_STATUS(buf,value)  buf[6] = value
//WRITE_CURRENT_IAC_LAP_status 1
#define WRITE_CURRENT_IAC_LAP_EVENT_PARAM_LENGTH 1 

#define SET_CE_SET_AFH_HOST_CHANNEL_CLASSIFICATION_STATUS(buf,value)  buf[6] = value
//SET_AFH_HOST_CHANNEL_CLASSIFICATION_status 1
#define SET_AFH_HOST_CHANNEL_CLASSIFICATION_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_INQUIRY_SCAN_TYPE_STATUS(buf,value)  buf[6] = value
//READ_INQUIRY_SCAN_TYPE_status 1
#define SET_CE_READ_INQUIRY_SCAN_TYPE_INQUIRY_SCAN_TYPE(buf,value)  buf[7] = value
//READ_INQUIRY_SCAN_TYPE_inquiry_scan_type 1
#define READ_INQUIRY_SCAN_TYPE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_INQUIRY_SCAN_TYPE_STATUS(buf,value)  buf[6] = value
//WRITE_INQUIRY_SCAN_TYPE_status 1
#define WRITE_INQUIRY_SCAN_TYPE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_INQUIRY_MODE_STATUS(buf,value)  buf[6] = value
//READ_INQUIRY_MODE_status 1
#define SET_CE_READ_INQUIRY_MODE_INQUIRY_MODE(buf,value)  buf[7] = value
//READ_INQUIRY_MODE_inquiry_mode 1
#define READ_INQUIRY_MODE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_INQUIRY_MODE_STATUS(buf,value)  buf[6] = value
//WRITE_INQUIRY_MODE_status 1
#define WRITE_INQUIRY_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_PAGE_SCAN_TYPE_STATUS(buf,value)  buf[6] = value
//READ_PAGE_SCAN_TYPE_status 1
#define SET_CE_READ_PAGE_SCAN_TYPE_PAGE_SCAN_TYPE(buf,value)  buf[7] = value
//READ_PAGE_SCAN_TYPE_page_scan_type 1
#define READ_PAGE_SCAN_TYPE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_PAGE_SCAN_TYPE_STATUS(buf,value)  buf[6] = value
//WRITE_PAGE_SCAN_TYPE_status 1
#define WRITE_PAGE_SCAN_TYPE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_AFH_CHANNEL_ASSESSMENT_MODE_STATUS(buf,value)  buf[6] = value
//READ_AFH_CHANNEL_ASSESSMENT_MODE_status 1
#define SET_CE_READ_AFH_CHANNEL_ASSESSMENT_MODE_AFH_CHANNEL_ASSESSMENT_MODE(buf,value)  buf[7] = value
//READ_AFH_CHANNEL_ASSESSMENT_MODE_afh_channel_assessment_mode 1
#define READ_AFH_CHANNEL_ASSESSMENT_MODE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_STATUS(buf,value)  buf[6] = value
//WRITE_AFH_CHANNEL_ASSESSMENT_MODE_status 1
#define WRITE_AFH_CHANNEL_ASSESSMENT_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_EXTENDED_INQUIRY_RESPONSE_STATUS(buf,value)  buf[6] = value
//READ_EXTENDED_INQUIRY_RESPONSE_status 1
#define SET_CE_READ_EXTENDED_INQUIRY_RESPONSE_FEC_REQUIRED(buf,value)  buf[7] = value
//READ_EXTENDED_INQUIRY_RESPONSE_fec_required 1
#define SET_CE_READ_EXTENDED_INQUIRY_RESPONSE_EXTENDED_INQUIRY_RESPONSE(buf,value)  memcpy((uint8_t *)&buf[8], &value, 240)
//READ_EXTENDED_INQUIRY_RESPONSE_extended_inquiry_response 240
#define READ_EXTENDED_INQUIRY_RESPONSE_EVENT_PARAM_LENGTH 242 

#define SET_CE_WRITE_EXTENDED_INQUIRY_RESPONSE_STATUS(buf,value)  buf[6] = value
//WRITE_EXTENDED_INQUIRY_RESPONSE_status 1
#define WRITE_EXTENDED_INQUIRY_RESPONSE_EVENT_PARAM_LENGTH 1 

#define SET_CE_REFRESH_ENCRYPTION_KEY_STATUS(buf,value)  buf[6] = value
#define REFRESH_ENCRYPTION_KEY_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_SIMPLE_PAIRING_MODE_STATUS(buf,value)  buf[6] = value
//READ_SIMPLE_PAIRING_MODE_status 1
#define SET_CE_READ_SIMPLE_PAIRING_MODE_SIMPLE_PAIRING_MODE(buf,value)  buf[7] = value
//READ_SIMPLE_PAIRING_MODE_simple_pairing_mode 1
#define READ_SIMPLE_PAIRING_MODE_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_SIMPLE_PAIRING_MODE_STATUS(buf,value)  buf[6] = value
//WRITE_SIMPLE_PAIRING_MODE_status 1
#define WRITE_SIMPLE_PAIRING_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_LOCAL_OOB_DATA_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_OOB_DATA_status 1
#define SET_CE_READ_LOCAL_OOB_DATA_C(buf,value)  memcpy((uint8_t *)&buf[7], &value, 16)
//READ_LOCAL_OOB_DATA_c 16
#define SET_CE_READ_LOCAL_OOB_DATA_R(buf,value)  memcpy((uint8_t *)&buf[23], &value, 16)
//READ_LOCAL_OOB_DATA_r 16
#define READ_LOCAL_OOB_DATA_EVENT_PARAM_LENGTH 33 

#define SET_CE_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_STATUS(buf,value)  buf[6] = value
//READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_status 1
#define SET_CE_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_TX_POWER(buf,value)  buf[7] = value
//READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_tx_power 1
#define READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_STATUS(buf,value)  buf[6] = value
//WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_status 1
#define WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_EVENT_PARAM_LENGTH 1 

#define SET_CE_SEND_KEYPRESS_NOTIFICATION_STATUS(buf,value)  buf[6] = value
//SEND_KEYPRESS_NOTIFICATION_status 1
#define SET_CE_SEND_KEYPRESS_NOTIFICATION_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//SEND_KEYPRESS_NOTIFICATION_bd_addr 6
#define SEND_KEYPRESS_NOTIFICATION_EVENT_PARAM_LENGTH 7 

#define SET_CE_ENHANCED_FLUSH_STATUS(buf,value)  buf[6] = value
#define ENHANCED_FLUSH_EVENT_PARAM_LENGTH 0 

#define SET_CE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_STATUS(buf,value)  buf[6] = value
//READ_ENHANCED_TRANSMIT_POWER_LEVEL_status 1
#define SET_CE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_ENHANCED_TRANSMIT_POWER_LEVEL_connection_handle 2
#define SET_CE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_TX_POWER_LEVEL_GFSK(buf,value)  buf[9] = value
//READ_ENHANCED_TRANSMIT_POWER_LEVEL_tx_power_level_gfsk 1
#define SET_CE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_TX_POWER_LEVEL_DQPSK(buf,value)  buf[10] = value
//READ_ENHANCED_TRANSMIT_POWER_LEVEL_tx_power_level_dqpsk 1
#define SET_CE_READ_ENHANCED_TRANSMIT_POWER_LEVEL_TX_POWER_LEVEL_8DPSK(buf,value)  buf[11] = value
//READ_ENHANCED_TRANSMIT_POWER_LEVEL_tx_power_level_8dpsk 1
#define READ_ENHANCED_TRANSMIT_POWER_LEVEL_EVENT_PARAM_LENGTH 6 

#define SET_CE_READ_SECURE_CONNECTIONS_HOST_SUPPORT_STATUS(buf,value)  buf[6] = value
//READ_SECURE_CONNECTIONS_HOST_SUPPORT_status 1
#define SET_CE_READ_SECURE_CONNECTIONS_HOST_SUPPORT_SECURE_CONNECTIONS_HOST_SUPPORT(buf,value)  buf[7] = value
//READ_SECURE_CONNECTIONS_HOST_SUPPORT_secure_connections_host_support 1
#define READ_SECURE_CONNECTIONS_HOST_SUPPORT_EVENT_PARAM_LENGTH 2 

#define SET_CE_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_STATUS(buf,value)  buf[6] = value
//WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_status 1
#define WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_EXTENDED_PAGE_TIMEOUT_STATUS(buf,value)  buf[6] = value
//READ_EXTENDED_PAGE_TIMEOUT_status 1
#define SET_CE_READ_EXTENDED_PAGE_TIMEOUT_EXTENDED_PAGE_TIMEOUT(buf,value)  *(uint16_t *)&buf[7] =value
//READ_EXTENDED_PAGE_TIMEOUT_extended_page_timeout 2
#define READ_EXTENDED_PAGE_TIMEOUT_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_EXTENDED_PAGE_TIMEOUT_STATUS(buf,value)  buf[6] = value
//WRITE_EXTENDED_PAGE_TIMEOUT_status 1
#define WRITE_EXTENDED_PAGE_TIMEOUT_EVENT_PARAM_LENGTH 1 

#define SET_CE_READ_EXTENDED_INQUIRY_LENGTH_STATUS(buf,value)  buf[6] = value
//READ_EXTENDED_INQUIRY_LENGTH_status 1
#define SET_CE_READ_EXTENDED_INQUIRY_LENGTH_EXTENDED_INQUIRY_LENGTH(buf,value)  *(uint16_t *)&buf[7] =value
//READ_EXTENDED_INQUIRY_LENGTH_extended_inquiry_length 2
#define READ_EXTENDED_INQUIRY_LENGTH_EVENT_PARAM_LENGTH 3 

#define SET_CE_WRITE_EXTENDED_INQUIRY_LENGTH_STATUS(buf,value)  buf[6] = value
//WRITE_EXTENDED_INQUIRY_LENGTH_status 1
#define WRITE_EXTENDED_INQUIRY_LENGTH_EVENT_PARAM_LENGTH 1 


/* INFORMATIONAL_PARAMETERS RETURN_PARAMETERS */

#define SET_CE_READ_LOCAL_VERSION_INFORMATION_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_VERSION_INFORMATION_status 1
#define SET_CE_READ_LOCAL_VERSION_INFORMATION_HCI_VERSION(buf,value)  buf[7] = value
//READ_LOCAL_VERSION_INFORMATION_hci_version 1
#define SET_CE_READ_LOCAL_VERSION_INFORMATION_HCI_SUBVERSION(buf,value)  *(uint16_t *)&buf[8] =value
//READ_LOCAL_VERSION_INFORMATION_hci_subversion 2
#define SET_CE_READ_LOCAL_VERSION_INFORMATION_LMP_VERSION(buf,value)  buf[10] = value
//READ_LOCAL_VERSION_INFORMATION_lmp_version 1
#define SET_CE_READ_LOCAL_VERSION_INFORMATION_COMPANY_IDENTIFIER(buf,value)  *(uint16_t *)&buf[11] =value
//READ_LOCAL_VERSION_INFORMATION_company_identifier 2
#define SET_CE_READ_LOCAL_VERSION_INFORMATION_LMP_SUBVERSION(buf,value)  *(uint16_t *)&buf[13] =value
//READ_LOCAL_VERSION_INFORMATION_lmp_subversion 2
#define READ_LOCAL_VERSION_INFORMATION_EVENT_PARAM_LENGTH 9 

#define SET_CE_READ_LOCAL_SUPPORTED_COMMANDS_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_SUPPORTED_COMMANDS_status 1
#define SET_CE_READ_LOCAL_SUPPORTED_COMMANDS_SUPPORTED_COMMANDS(buf,value)  memcpy((uint8_t *)&buf[7], &value, 64)
//READ_LOCAL_SUPPORTED_COMMANDS_supported_commands 64
#define READ_LOCAL_SUPPORTED_COMMANDS_EVENT_PARAM_LENGTH 65 

#define SET_CE_READ_LOCAL_SUPPORTED_FEATURES_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_SUPPORTED_FEATURES_status 1
#define SET_CE_READ_LOCAL_SUPPORTED_FEATURES_LMP_FEATURES(buf,value)  memcpy((uint8_t *)&buf[7], &value, 8)
//READ_LOCAL_SUPPORTED_FEATURES_lmp_features 8
#define READ_LOCAL_SUPPORTED_FEATURES_EVENT_PARAM_LENGTH 9 

#define SET_CE_READ_LOCAL_EXTENDED_FEATURES_STATUS(buf,value)  buf[6] = value
//READ_LOCAL_EXTENDED_FEATURES_status 1
#define SET_CE_READ_LOCAL_EXTENDED_FEATURES_PAGE_NUMBER(buf,value)  buf[7] = value
//READ_LOCAL_EXTENDED_FEATURES_page_number 1
#define SET_CE_READ_LOCAL_EXTENDED_FEATURES_MAX_PAGE_NUMBER(buf,value)  buf[8] = value
//READ_LOCAL_EXTENDED_FEATURES_max_page_number 1
#define SET_CE_READ_LOCAL_EXTENDED_FEATURES_EXTENDED_LMP_FEATURES(buf,value)  memcpy((uint8_t *)&buf[9], &value, 8)
//READ_LOCAL_EXTENDED_FEATURES_extended_lmp_features 8
#define READ_LOCAL_EXTENDED_FEATURES_EVENT_PARAM_LENGTH 11 

#define SET_CE_READ_BUFFER_SIZE_STATUS(buf,value)  buf[6] = value
//READ_BUFFER_SIZE_status 1
#define SET_CE_READ_BUFFER_SIZE_ACL_DATA_PACKET_LENGTH(buf,value)  *(uint16_t *)&buf[7] =value
//READ_BUFFER_SIZE_acl_data_packet_length 2
#define SET_CE_READ_BUFFER_SIZE_SYNCHRONOUS_DATA_PACKET_LENGTH(buf,value)  buf[9] = value
//READ_BUFFER_SIZE_synchronous_data_packet_length 1
#define SET_CE_READ_BUFFER_SIZE_TOTAL_NUM_ACL_DATA_PACKETS(buf,value)  *(uint16_t *)&buf[10] =value
//READ_BUFFER_SIZE_total_num_acl_data_packets 2
#define SET_CE_READ_BUFFER_SIZE_HOST_TOTAL_NUM_SYNCHRONOUS_DATA_PACKETS(buf,value)  *(uint16_t *)&buf[12] =value
//READ_BUFFER_SIZE_host_total_num_synchronous_data_packets 2
#define READ_BUFFER_SIZE_EVENT_PARAM_LENGTH 8 

#define SET_CE_READ_BD_ADDR_STATUS(buf,value)  buf[6] = value
//READ_BD_ADDR_status 1
#define SET_CE_READ_BD_ADDR_BD_ADDR(buf,value)  memcpy((uint8_t *)&buf[7], &value, 6)
//READ_BD_ADDR_bd_addr 6
#define READ_BD_ADDR_EVENT_PARAM_LENGTH 7 


/* STATUS_PARAMETERS RETURN_PARAMETERS */

#define SET_CE_READ_LINK_QUALITY_STATUS(buf,value)  buf[6] = value
//READ_LINK_QUALITY_status 1
#define SET_CE_READ_LINK_QUALITY_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_LINK_QUALITY_handle 2
#define SET_CE_READ_LINK_QUALITY_LINK_QUALITY(buf,value)  buf[9] = value
//READ_LINK_QUALITY_link_quality 1
#define READ_LINK_QUALITY_EVENT_PARAM_LENGTH 4 

#define SET_CE_READ_RSSI_STATUS(buf,value)  buf[6] = value
//READ_RSSI_status 1
#define SET_CE_READ_RSSI_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_RSSI_handle 2
#define SET_CE_READ_RSSI_RSSI(buf,value)  buf[9] = value
//READ_RSSI_rssi 1
#define READ_RSSI_EVENT_PARAM_LENGTH 4 

#define SET_CE_READ_AFH_CHANNEL_MAP_STATUS(buf,value)  buf[6] = value
//READ_AFH_CHANNEL_MAP_status 1
#define SET_CE_READ_AFH_CHANNEL_MAP_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_AFH_CHANNEL_MAP_connection_handle 2
#define SET_CE_READ_AFH_CHANNEL_MAP_AFH_MODE(buf,value)  buf[9] = value
//READ_AFH_CHANNEL_MAP_afh_mode 1
#define SET_CE_READ_AFH_CHANNEL_MAP_AFH_CHANNEL_MAP(buf,value)  memcpy((uint8_t *)&buf[10], &value, 10)
//READ_AFH_CHANNEL_MAP_afh_channel_map 10
#define READ_AFH_CHANNEL_MAP_EVENT_PARAM_LENGTH 14 

#define SET_CE_READ_CLOCK_STATUS(buf,value)  buf[6] = value
//READ_CLOCK_status 1
#define SET_CE_READ_CLOCK_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_CLOCK_connection_handle 2
#define SET_CE_READ_CLOCK_CLOCK(buf,value)  *(uint32_t *)&buf[9] = value
//READ_CLOCK_clock 4
#define SET_CE_READ_CLOCK_ACCURACY(buf,value)  *(uint16_t *)&buf[13] =value
//READ_CLOCK_accuracy 2
#define READ_CLOCK_EVENT_PARAM_LENGTH 9 

#define SET_CE_READ_ENCRYPTION_KEY_SIZE_STATUS(buf,value)  buf[6] = value
//READ_ENCRYPTION_KEY_SIZE_status 1
#define SET_CE_READ_ENCRYPTION_KEY_SIZE_CONNECTION_HANDLE(buf,value)  *(uint16_t *)&buf[7] =value
//READ_ENCRYPTION_KEY_SIZE_connection_handle 2
#define SET_CE_READ_ENCRYPTION_KEY_SIZE_KEY_SIZE(buf,value)  buf[9] = value
//READ_ENCRYPTION_KEY_SIZE_key_size 1
#define READ_ENCRYPTION_KEY_SIZE_EVENT_PARAM_LENGTH 4 


/* TEST_COMMANDS RETURN_PARAMETERS */

#define SET_CE_ENABLE_DEVICE_UNDER_TEST_MODE_STATUS(buf,value)  buf[6] = value
//ENABLE_DEVICE_UNDER_TEST_MODE_status 1
#define ENABLE_DEVICE_UNDER_TEST_MODE_EVENT_PARAM_LENGTH 1 

#define SET_CE_WRITE_SIMPLE_PAIRING_DEBUG_MODE_STATUS(buf,value)  buf[6] = value
//WRITE_SIMPLE_PAIRING_DEBUG_MODE_status 1
#define WRITE_SIMPLE_PAIRING_DEBUG_MODE_EVENT_PARAM_LENGTH 1 


/* VENDOR_SPECIFIC RETURN_PARAMETERS */

#define SET_CE_ECHO_STATUS(buf,value)  buf[6] = value
#define ECHO_EVENT_PARAM_LENGTH 0 

#define SET_CE_VIRTUAL_LISTEN_CONNECTION_STATUS(buf,value)  buf[6] = value
#define VIRTUAL_LISTEN_CONNECTION_EVENT_PARAM_LENGTH 0 

#define SET_CE_VIRTUAL_CANCEL_LISTEN_STATUS(buf,value)  buf[6] = value
#define VIRTUAL_CANCEL_LISTEN_EVENT_PARAM_LENGTH 0 

#define SET_CE_VIRTUAL_CONNECT_STATUS(buf,value)  buf[6] = value
#define VIRTUAL_CONNECT_EVENT_PARAM_LENGTH 0 

#define SET_CE_VIRTUAL_CANCEL_CONNECT_STATUS(buf,value)  buf[6] = value
#define VIRTUAL_CANCEL_CONNECT_EVENT_PARAM_LENGTH 0 

#define SET_CE_INTERNAL_EVENT_TRIGGER_FROM_LPW_STATUS(buf,value)  buf[6] = value
#define INTERNAL_EVENT_TRIGGER_FROM_LPW_EVENT_PARAM_LENGTH 0 

#define SET_CE_KILL_FIRMWARE_STATUS(buf,value)  buf[6] = value
#define KILL_FIRMWARE_EVENT_PARAM_LENGTH 0 

#define SET_CE_SET_LOCAL_LMP_FEATURES_STATUS(buf,value)  buf[6] = value
#define SET_LOCAL_LMP_FEATURES_EVENT_PARAM_LENGTH 0 



#endif