#include "hci_handlers_autogen.h"
#include <hci.h>

/* -------------------link_control_handlers---------------------*/
hci_handler_t link_control_lut[] = { 
NULL,
hci_cmd_inquiry_handler,
hci_cmd_inquiry_cancel_handler,
hci_cmd_periodic_inquiry_mode_handler,
hci_cmd_exit_periodic_inquiry_mode_handler,
hci_cmd_create_connection_handler,
hci_cmd_disconnect_handler,
NULL,
hci_cmd_create_connection_cancel_handler,
hci_cmd_accept_connection_request_handler,
hci_cmd_reject_connection_request_handler,
hci_cmd_link_key_request_reply_handler,
hci_cmd_link_key_request_negative_reply_handler,
hci_cmd_pin_code_request_reply_handler,
hci_cmd_pin_code_request_negative_reply_handler,
hci_cmd_change_connection_packet_type_handler,
NULL,
hci_cmd_authentication_requested_handler,
NULL,
hci_cmd_set_connection_encryption_handler,
NULL,
hci_cmd_change_connection_link_key_handler,
NULL,
NULL,
NULL,
hci_cmd_remote_name_request_handler,
hci_cmd_remote_name_request_cancel_handler,
hci_cmd_read_remote_supported_features_handler,
hci_cmd_read_remote_extended_features_handler,
hci_cmd_read_remote_version_information_handler,
NULL,
hci_cmd_read_clock_offset_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_setup_synchronous_connection_handler,
hci_cmd_accept_synchronous_connection_request_handler,
hci_cmd_reject_synchronous_connection_request_handler,
hci_cmd_io_capability_request_reply_handler,
hci_cmd_user_confirmation_request_reply_handler,
hci_cmd_user_confirmation_request_negative_reply_handler,
hci_cmd_user_passkey_request_reply_handler,
hci_cmd_user_passkey_request_negative_reply_handler,
hci_cmd_remote_oob_data_request_reply_handler,
NULL,
NULL,
hci_cmd_remote_oob_data_request_negative_reply_handler,
hci_cmd_io_capability_request_negative_reply_handler,
};


/* -------------------link_policy_handlers---------------------*/
hci_handler_t link_policy_lut[] = { 
NULL,
NULL,
NULL,
hci_cmd_sniff_mode_handler,
hci_cmd_exit_sniff_mode_handler,
NULL,
NULL,
hci_cmd_qos_setup_handler,
NULL,
hci_cmd_role_discovery_handler,
NULL,
hci_cmd_switch_role_handler,
hci_cmd_read_link_policy_settings_handler,
hci_cmd_write_link_policy_settings_handler,
hci_cmd_read_default_link_policy_settings_handler,
hci_cmd_write_default_link_policy_settings_handler,
NULL,
NULL,
hci_cmd_sniff_subrating_handler,
};


/* -------------------controller_and_baseband_handlers---------------------*/
hci_handler_t controller_and_baseband_lut[] = { 
NULL,
hci_cmd_set_event_mask_handler,
NULL,
hci_cmd_reset_handler,
NULL,
hci_cmd_set_event_filter_handler,
NULL,
NULL,
NULL,
hci_cmd_read_pin_type_handler,
hci_cmd_write_pin_type_handler,
NULL,
NULL,
hci_cmd_read_stored_link_key_handler,
NULL,
NULL,
NULL,
hci_cmd_write_stored_link_key_handler,
hci_cmd_delete_stored_link_key_handler,
hci_cmd_write_local_name_handler,
hci_cmd_read_local_name_handler,
hci_cmd_read_connection_accept_timeout_handler,
hci_cmd_write_connection_accept_timeout_handler,
hci_cmd_read_page_timeout_handler,
hci_cmd_write_page_timeout_handler,
hci_cmd_read_scan_enable_handler,
hci_cmd_write_scan_enable_handler,
hci_cmd_read_page_scan_activity_handler,
hci_cmd_write_page_scan_activity_handler,
hci_cmd_read_inquiry_scan_activity_handler,
hci_cmd_write_inquiry_scan_activity_handler,
hci_cmd_read_authentication_enable_handler,
hci_cmd_write_authentication_enable_handler,
NULL,
NULL,
hci_cmd_read_class_of_device_handler,
hci_cmd_write_class_of_device_handler,
hci_cmd_read_voice_setting_handler,
hci_cmd_write_voice_setting_handler,
hci_cmd_read_automatic_flush_timeout_handler,
hci_cmd_write_automatic_flush_timeout_handler,
NULL,
NULL,
NULL,
NULL,
hci_cmd_read_transmit_power_level_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_read_link_supervision_timeout_handler,
hci_cmd_write_link_supervision_timeout_handler,
hci_cmd_read_number_of_supported_iac_handler,
hci_cmd_read_current_iac_lap_handler,
hci_cmd_write_current_iac_lap_handler,
NULL,
NULL,
NULL,
NULL,
hci_cmd_set_afh_host_channel_classification_handler,
NULL,
NULL,
hci_cmd_read_inquiry_scan_type_handler,
hci_cmd_write_inquiry_scan_type_handler,
hci_cmd_read_inquiry_mode_handler,
hci_cmd_write_inquiry_mode_handler,
hci_cmd_read_page_scan_type_handler,
hci_cmd_write_page_scan_type_handler,
hci_cmd_read_afh_channel_assessment_mode_handler,
hci_cmd_write_afh_channel_assessment_mode_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_read_extended_inquiry_response_handler,
hci_cmd_write_extended_inquiry_response_handler,
hci_cmd_refresh_encryption_key_handler,
NULL,
hci_cmd_read_simple_pairing_mode_handler,
hci_cmd_write_simple_pairing_mode_handler,
hci_cmd_read_local_oob_data_handler,
hci_cmd_read_inquiry_response_transmit_power_level_handler,
hci_cmd_write_inquiry_transmit_power_level_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_send_keypress_notification_handler,
hci_cmd_enhanced_flush_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_read_enhanced_transmit_power_level_handler,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
hci_cmd_read_secure_connections_host_support_handler,
hci_cmd_write_secure_connections_host_support_handler,
NULL,
NULL,
NULL,
hci_cmd_read_extended_page_timeout_handler,
hci_cmd_write_extended_page_timeout_handler,
hci_cmd_read_extended_inquiry_length_handler,
hci_cmd_write_extended_inquiry_length_handler,
};


/* -------------------informational_parameters_handlers---------------------*/
hci_handler_t informational_parameters_lut[] = { 
NULL,
hci_cmd_read_local_version_information_handler,
hci_cmd_read_local_supported_commands_handler,
hci_cmd_read_local_supported_features_handler,
hci_cmd_read_local_extended_features_handler,
hci_cmd_read_buffer_size_handler,
NULL,
NULL,
NULL,
hci_cmd_read_bd_addr_handler,
};


/* -------------------status_parameters_handlers---------------------*/
hci_handler_t status_parameters_lut[] = { 
NULL,
NULL,
NULL,
hci_cmd_read_link_quality_handler,
NULL,
hci_cmd_read_rssi_handler,
hci_cmd_read_afh_channel_map_handler,
hci_cmd_read_clock_handler,
hci_cmd_read_encryption_key_size_handler,
};


/* -------------------test_commands_handlers---------------------*/
hci_handler_t test_commands_lut[] = { 
NULL,
NULL,
NULL,
hci_cmd_enable_device_under_test_mode_handler,
hci_cmd_write_simple_pairing_debug_mode_handler,
};


/* -------------------vendor_specific_handlers---------------------*/
hci_handler_t vendor_specific_lut[] = { 
NULL,
hci_cmd_vendor_echo_handler,
hci_cmd_vendor_virtual_listen_connection_handler,
hci_cmd_vendor_virtual_cancel_listen_handler,
hci_cmd_vendor_virtual_connect_handler,
hci_cmd_vendor_virtual_cancel_connect_handler,
hci_cmd_vendor_internal_event_trigger_from_lpw_handler,
hci_cmd_vendor_kill_firmware_handler,
hci_cmd_vendor_set_local_lmp_features_handler,
};


hci_handler_t *hci_ogf_lut[] = 
{
    NULL,
    link_control_lut,
    link_policy_lut,
    controller_and_baseband_lut,
    informational_parameters_lut,
    status_parameters_lut,
    test_commands_lut,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    vendor_specific_lut,
};

uint16_t sizes_of_groups[]={
    0,
    53,
    19,
    130,
    10,
    9,
    5,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    9,
};


uint16_t size_of_recieved_group_lut(uint8_t ogf){
    return sizes_of_groups[ogf];
}

uint16_t size_of_hci_ogf_lut()
{
    return sizeof(hci_ogf_lut);
}
hci_handler_t *get_ocf_handlers_lut(uint8_t ogf)
{
    return hci_ogf_lut[ogf];
}