#ifndef LMP_GET_DEF_H
#define LMP_GET_DEF_H
#include <stdint.h>

/* LMP_NAME_REQ */
#define GET_LMP_NAME_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_NAME_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_NAME_REQ_PARAMETER_NAME_OFFSET(buf)  buf[4] 
/* LMP_NAME_RES */
#define GET_LMP_NAME_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_NAME_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_NAME_RES_PARAMETER_NAME_OFFSET(buf)  buf[4] 
#define GET_LMP_NAME_RES_PARAMETER_NAME_LENGTH(buf)  buf[5] 
#define GET_LMP_NAME_RES_PARAMETER_NAME_FRAGMENT(buf)  (buf[6])
/* LMP_ACCEPTED */
#define GET_LMP_ACCEPTED_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ACCEPTED_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ACCEPTED_PARAMETER_OPCODE(buf)  buf[4] 
/* LMP_NOT_ACCEPTED */
#define GET_LMP_NOT_ACCEPTED_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_NOT_ACCEPTED_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_NOT_ACCEPTED_PARAMETER_OPCODE(buf)  buf[4] 
#define GET_LMP_NOT_ACCEPTED_PARAMETER_ERROR_OPCODE(buf)  buf[5] 
/* LMP_CLKOFFSET_REQ */
#define GET_LMP_CLKOFFSET_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CLKOFFSET_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_CLKOFFSET_RES */
#define GET_LMP_CLKOFFSET_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CLKOFFSET_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_CLKOFFSET_RES_PARAMETER_CLOCK_OFFSET(buf)  ((uint16_t *)&buf[4]) 
/* LMP_DETACH */
#define GET_LMP_DETACH_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_DETACH_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_DETACH_PARAMETER_ERROR_CODE(buf)  buf[4] 
/* LMP_IN_RAND */
#define GET_LMP_IN_RAND_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_IN_RAND_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_IN_RAND_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_COMB_KEY */
#define GET_LMP_COMB_KEY_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_COMB_KEY_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_COMB_KEY_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_UNIT_KEY */
#define GET_LMP_UNIT_KEY_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_UNIT_KEY_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_UNIT_KEY_PARAMETER_KEY(buf)  (buf[4])
/* LMP_AU_RAND */
#define GET_LMP_AU_RAND_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_AU_RAND_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_AU_RAND_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_SRES */
#define GET_LMP_SRES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SRES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SRES_PARAMETER_AUTHENTICATION_RSP(buf)  (uint32_t *)&buf[4] 
/* LMP_TEMP_RAND */
#define GET_LMP_TEMP_RAND_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TEMP_RAND_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_TEMP_RAND_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_TEMP_KEY */
#define GET_LMP_TEMP_KEY_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TEMP_KEY_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_TEMP_KEY_PARAMETER_KEY(buf)  (buf[4])
/* LMP_ENCRYPTION_MODE_REQ */
#define GET_LMP_ENCRYPTION_MODE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCRYPTION_MODE_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ENCRYPTION_MODE_REQ_PARAMETER_ENCRYPTION_MODE(buf)  buf[4] 
/* LMP_ENCRYPTION_KEY_SIZE_REQ */
#define GET_LMP_ENCRYPTION_KEY_SIZE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCRYPTION_KEY_SIZE_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ENCRYPTION_KEY_SIZE_REQ_PARAMETER_KEY_SIZE(buf)  buf[4] 
/* LMP_START_ENCRYPTION_REQ */
#define GET_LMP_START_ENCRYPTION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_START_ENCRYPTION_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_START_ENCRYPTION_REQ_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_STOP_ENCRYPTION_REQ */
#define GET_LMP_STOP_ENCRYPTION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_STOP_ENCRYPTION_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_SWITCH_REQ */
#define GET_LMP_SWITCH_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SWITCH_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SWITCH_REQ_PARAMETER_SWITCH_INSTANT(buf)  (uint32_t *)&buf[4] 
/* LMP_HOLD */
#define GET_LMP_HOLD_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_HOLD_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_HOLD_PARAMETER_HOLD_TIME(buf)  ((uint16_t *)&buf[4]) 
#define GET_LMP_HOLD_PARAMETER_HOLD_INSTANT(buf)  (uint32_t *)&buf[6] 
/* LMP_HOLD_REQ */
#define GET_LMP_HOLD_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_HOLD_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_HOLD_REQ_PARAMETER_HOLD_TIME(buf)  ((uint16_t *)&buf[4]) 
#define GET_LMP_HOLD_REQ_PARAMETER_HOLD_INSTANT(buf)  (uint32_t *)&buf[6] 
/* LMP_SNIFF_REQ */
#define GET_LMP_SNIFF_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SNIFF_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SNIFF_REQ_PARAMETER_TIMING_CONTROL_FLAGS_1(buf)  buf[4] 
#define GET_LMP_SNIFF_REQ_PARAMETER_D_SNIFF(buf)  ((uint16_t *)&buf[5]) 
#define GET_LMP_SNIFF_REQ_PARAMETER_T_SNIFF(buf)  ((uint16_t *)&buf[7]) 
#define GET_LMP_SNIFF_REQ_PARAMETER_TIMING_CONTROL_FLAGS_2(buf)  ((uint16_t *)&buf[9]) 
#define GET_LMP_SNIFF_REQ_PARAMETER_SNIFF_TIMEOUT(buf)  ((uint16_t *)&buf[11]) 
/* LMP_UNSNIFF_REQ */
#define GET_LMP_UNSNIFF_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_UNSNIFF_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_INCR_POWER_REQ */
#define GET_LMP_INCR_POWER_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_INCR_POWER_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_INCR_POWER_REQ_PARAMETER_RESERVED(buf)  buf[4] 
/* LMP_DECR_POWER_REQ */
#define GET_LMP_DECR_POWER_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_DECR_POWER_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_DECR_POWER_REQ_PARAMETER_RESERVED(buf)  buf[4] 
/* LMP_MAX_POWER */
#define GET_LMP_MAX_POWER_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_MAX_POWER_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_MIN_POWER */
#define GET_LMP_MIN_POWER_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_MIN_POWER_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_AUTO_RATE */
#define GET_LMP_AUTO_RATE_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_AUTO_RATE_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_PREFERRED_RATE */
#define GET_LMP_PREFERRED_RATE_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PREFERRED_RATE_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_PREFERRED_RATE_PARAMETER_DATA_RATE(buf)  buf[4] 
/* LMP_VERSION_REQ */
#define GET_LMP_VERSION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_VERSION_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_VERSION_REQ_PARAMETER_VERSION(buf)  buf[4] 
#define GET_LMP_VERSION_REQ_PARAMETER_COMPANY_IDENTIFIER(buf)  ((uint16_t *)&buf[5]) 
#define GET_LMP_VERSION_REQ_PARAMETER_SUBVERSION(buf)  ((uint16_t *)&buf[7]) 
/* LMP_VERSION_RES */
#define GET_LMP_VERSION_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_VERSION_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_VERSION_RES_PARAMETER_VERSION(buf)  buf[4] 
#define GET_LMP_VERSION_RES_PARAMETER_COMPANY_IDENTIFIER(buf)  ((uint16_t *)&buf[5]) 
#define GET_LMP_VERSION_RES_PARAMETER_SUBVERSION(buf)  ((uint16_t *)&buf[7]) 
/* LMP_FEATURES_REQ */
#define GET_LMP_FEATURES_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_FEATURES_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_FEATURES_REQ_PARAMETER_FEATURES(buf)  (buf[4])
/* LMP_FEATURES_RES */
#define GET_LMP_FEATURES_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_FEATURES_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_FEATURES_RES_PARAMETER_FEATURES(buf)  (buf[4])
/* LMP_QUALITY_OF_SERVICE */
#define GET_LMP_QUALITY_OF_SERVICE_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_QUALITY_OF_SERVICE_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_QUALITY_OF_SERVICE_PARAMETER_POLL_INTERVAL(buf)  ((uint16_t *)&buf[4]) 
#define GET_LMP_QUALITY_OF_SERVICE_PARAMETER_N_BC(buf)  buf[6] 
/* LMP_QUALITY_OF_SERVICE_REQ */
#define GET_LMP_QUALITY_OF_SERVICE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_QUALITY_OF_SERVICE_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_QUALITY_OF_SERVICE_REQ_PARAMETER_POLL_INTERVAL(buf)  ((uint16_t *)&buf[4]) 
#define GET_LMP_QUALITY_OF_SERVICE_REQ_PARAMETER_N_BC(buf)  buf[6] 
/* LMP_SCO_LINK_REQ */
#define GET_LMP_SCO_LINK_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SCO_LINK_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SCO_LINK_REQ_PARAMETER_SCO_HANDLE(buf)  buf[4] 
#define GET_LMP_SCO_LINK_REQ_PARAMETER_TIMING_CONTROL_FLAGS(buf)  buf[5] 
#define GET_LMP_SCO_LINK_REQ_PARAMETER_D_SCO(buf)  buf[6] 
#define GET_LMP_SCO_LINK_REQ_PARAMETER_T_SCO(buf)  buf[7] 
#define GET_LMP_SCO_LINK_REQ_PARAMETER_SCO_PACKET(buf)  buf[8] 
#define GET_LMP_SCO_LINK_REQ_PARAMETER_AIR_MODE(buf)  buf[9] 
/* LMP_REMOVE_SCO_LINK_REQ */
#define GET_LMP_REMOVE_SCO_LINK_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_REMOVE_SCO_LINK_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_REMOVE_SCO_LINK_REQ_PARAMETER_SCO_HANDLE(buf)  buf[4] 
#define GET_LMP_REMOVE_SCO_LINK_REQ_PARAMETER_ERROR_CODE(buf)  buf[5] 
/* LMP_MAX_SLOT */
#define GET_LMP_MAX_SLOT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_MAX_SLOT_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_MAX_SLOT_PARAMETER_MAX_SLOTS(buf)  buf[4] 
/* LMP_MAX_SLOT_REQ */
#define GET_LMP_MAX_SLOT_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_MAX_SLOT_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_MAX_SLOT_REQ_PARAMETER_MAX_SLOTS(buf)  buf[4] 
/* LMP_TIMIMG_ACCURACY_REQ */
#define GET_LMP_TIMIMG_ACCURACY_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TIMIMG_ACCURACY_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_TIMING_ACCURACY_RES */
#define GET_LMP_TIMING_ACCURACY_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TIMING_ACCURACY_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_TIMING_ACCURACY_RES_PARAMETER_DRIFT(buf)  buf[4] 
#define GET_LMP_TIMING_ACCURACY_RES_PARAMETER_JITTER(buf)  buf[5] 
/* LMP_SETUP_COMPLETE */
#define GET_LMP_SETUP_COMPLETE_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SETUP_COMPLETE_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_USE_SEMI_PERMANENT_KEY */
#define GET_LMP_USE_SEMI_PERMANENT_KEY_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_USE_SEMI_PERMANENT_KEY_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_HOST_CONNECTION_REQ */
#define GET_LMP_HOST_CONNECTION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_HOST_CONNECTION_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_SLOT_OFFSET */
#define GET_LMP_SLOT_OFFSET_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SLOT_OFFSET_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SLOT_OFFSET_PARAMETER_SLOT_OFFSET(buf)  ((uint16_t *)&buf[4]) 
#define GET_LMP_SLOT_OFFSET_PARAMETER_BD_ADDR(buf)  (buf[6])
/* LMP_PAGE_MODE_REQ */
#define GET_LMP_PAGE_MODE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PAGE_MODE_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_PAGE_MODE_REQ_PARAMETER_PAGE_SCHEME(buf)  buf[4] 
#define GET_LMP_PAGE_MODE_REQ_PARAMETER_PAGE_SCHEME_SETTING(buf)  buf[5] 
/* LMP_PAGE_SCAN_MODE_REQ */
#define GET_LMP_PAGE_SCAN_MODE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PAGE_SCAN_MODE_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_PAGE_SCAN_MODE_REQ_PARAMETER_PAGE_SCHEME(buf)  buf[4] 
#define GET_LMP_PAGE_SCAN_MODE_REQ_PARAMETER_PAGE_SCHEME_SETTING(buf)  buf[5] 
/* LMP_SUPERVISION_TIMEOUT */
#define GET_LMP_SUPERVISION_TIMEOUT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SUPERVISION_TIMEOUT_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SUPERVISION_TIMEOUT_PARAMETER_SUPERVISION_TIMEOUT(buf)  ((uint16_t *)&buf[4]) 
/* LMP_TEST_ACTIVATE */
#define GET_LMP_TEST_ACTIVATE_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TEST_ACTIVATE_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_TEST_CONTROL */
#define GET_LMP_TEST_CONTROL_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_TEST_CONTROL_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_TEST_CONTROL_PARAMETER_TEST_SENARIO(buf)  buf[4] 
#define GET_LMP_TEST_CONTROL_PARAMETER_HOPPING_MODE(buf)  buf[5] 
#define GET_LMP_TEST_CONTROL_PARAMETER_TX_FREQUENCY(buf)  buf[6] 
#define GET_LMP_TEST_CONTROL_PARAMETER_RX_FREQUENCY(buf)  buf[7] 
#define GET_LMP_TEST_CONTROL_PARAMETER_POWER_MODE(buf)  buf[8] 
#define GET_LMP_TEST_CONTROL_PARAMETER_POLL_PERIOD(buf)  buf[9] 
#define GET_LMP_TEST_CONTROL_PARAMETER_PACKET_TYPE(buf)  buf[10] 
#define GET_LMP_TEST_CONTROL_PARAMETER_TEST_DATA_LENGTH(buf)  ((uint16_t *)&buf[11]) 
/* LMP_ENCRYPTION_KEY_SIZE_MASK_REQ */
#define GET_LMP_ENCRYPTION_KEY_SIZE_MASK_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCRYPTION_KEY_SIZE_MASK_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
/* LMP_ENCRYPTION_KEY_SIZE_MASK_RES */
#define GET_LMP_ENCRYPTION_KEY_SIZE_MASK_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCRYPTION_KEY_SIZE_MASK_RES_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ENCRYPTION_KEY_SIZE_MASK_RES_PARAMETER_KEY_SIZE_MASK(buf)  ((uint16_t *)&buf[4]) 
/* LMP_SET_AFH */
#define GET_LMP_SET_AFH_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SET_AFH_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SET_AFH_PARAMETER_AFH_INSTANT(buf)  (uint32_t *)&buf[4] 
#define GET_LMP_SET_AFH_PARAMETER_AFH_MODE(buf)  buf[8] 
#define GET_LMP_SET_AFH_PARAMETER_AFH_CHANNEL_MAP(buf)  (buf[9])
/* LMP_ENCAPSULATED_HEADER */
#define GET_LMP_ENCAPSULATED_HEADER_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCAPSULATED_HEADER_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ENCAPSULATED_HEADER_PARAMETER_ENCAP_MAJOR_TYPE(buf)  buf[4] 
#define GET_LMP_ENCAPSULATED_HEADER_PARAMETER_ENCAP_MINOR_TYPE(buf)  buf[5] 
#define GET_LMP_ENCAPSULATED_HEADER_PARAMETER_ENCAP_PAYLOAD_LENGTH(buf)  buf[6] 
/* LMP_ENCAPSULATED_PAYLOAD */
#define GET_LMP_ENCAPSULATED_PAYLOAD_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ENCAPSULATED_PAYLOAD_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_ENCAPSULATED_PAYLOAD_PARAMETER_ENCAP_DATA(buf)  (buf[4])
/* LMP_SIMPLE_PAIRING_CONFIRM */
#define GET_LMP_SIMPLE_PAIRING_CONFIRM_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SIMPLE_PAIRING_CONFIRM_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SIMPLE_PAIRING_CONFIRM_PARAMETER_COMMITMENT_VALUE(buf)  (buf[4])
/* LMP_SIMPLE_PAIRING_NUMBER */
#define GET_LMP_SIMPLE_PAIRING_NUMBER_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SIMPLE_PAIRING_NUMBER_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_SIMPLE_PAIRING_NUMBER_PARAMETER_NONCVALUE(buf)  (buf[4])
/* LMP_DHKEY_CHECK */
#define GET_LMP_DHKEY_CHECK_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_DHKEY_CHECK_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_DHKEY_CHECK_PARAMETER_CONFIRMATION_VALUE(buf)  (buf[4])
/* LMP_PAUSE_ENCRYPTION_AES_REQ */
#define GET_LMP_PAUSE_ENCRYPTION_AES_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PAUSE_ENCRYPTION_AES_REQ_OPCODE(buf) ((buf[3]) & ~(BIT(7)))
#define GET_LMP_PAUSE_ENCRYPTION_AES_REQ_PARAMETER_RANDOM_NUMBER(buf)  (buf[4])
/* LMP_ACCEPTED_EXT */
#define GET_LMP_ACCEPTED_EXT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ACCEPTED_EXT_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_ACCEPTED_EXT_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_ACCEPTED_EXT_PARAMETER_EXTENDED_OPCODE(buf)  buf[5] 
/* LMP_NOT_ACCEPTED_EXT */
#define GET_LMP_NOT_ACCEPTED_EXT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_NOT_ACCEPTED_EXT_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_NOT_ACCEPTED_EXT_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_NOT_ACCEPTED_EXT_PARAMETER_EXTENDED_OPCODE(buf)  buf[5] 
#define GET_LMP_NOT_ACCEPTED_EXT_PARAMETER_ERROR_CODE(buf)  buf[6] 
/* LMP_FEATURES_REQ_EXT */
#define GET_LMP_FEATURES_REQ_EXT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_FEATURES_REQ_EXT_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_FEATURES_REQ_EXT_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_FEATURES_REQ_EXT_PARAMETER_FEATURES_PAGE(buf)  buf[5] 
#define GET_LMP_FEATURES_REQ_EXT_PARAMETER_MAX_SUPPORTED_PAGE(buf)  buf[6] 
#define GET_LMP_FEATURES_REQ_EXT_PARAMETER_EXTENDED_FEATURES(buf)  (buf[7])
/* LMP_FEATURES_RES_EXT */
#define GET_LMP_FEATURES_RES_EXT_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_FEATURES_RES_EXT_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_FEATURES_RES_EXT_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_FEATURES_RES_EXT_PARAMETER_FEATURES_PAGE(buf)  buf[5] 
#define GET_LMP_FEATURES_RES_EXT_PARAMETER_MAX_SUPPORTED_PAGE(buf)  buf[6] 
#define GET_LMP_FEATURES_RES_EXT_PARAMETER_EXTENDED_FEATURES(buf)  (buf[7])
/* LMP_CLK_ADJ */
#define GET_LMP_CLK_ADJ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CLK_ADJ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_CLK_ADJ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_ID(buf)  buf[5] 
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_INSTANT(buf)  (uint32_t *)&buf[6] 
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_OFFSET(buf)  ((uint16_t *)&buf[10]) 
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_SLOTS(buf)  buf[12] 
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_MODE(buf)  buf[13] 
#define GET_LMP_CLK_ADJ_PARAMETER_CLK_ADJ_CLK(buf)  (uint32_t *)&buf[14] 
/* LMP_CLK_ADJ_ACK */
#define GET_LMP_CLK_ADJ_ACK_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CLK_ADJ_ACK_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_CLK_ADJ_ACK_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_CLK_ADJ_ACK_PARAMETER_CLK_ADJ_ID(buf)  buf[5] 
/* LMP_CLK_ADJ_REQ */
#define GET_LMP_CLK_ADJ_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CLK_ADJ_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_CLK_ADJ_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_CLK_ADJ_REQ_PARAMETER_CLK_ADJ_OFFSET(buf)  ((uint16_t *)&buf[5]) 
#define GET_LMP_CLK_ADJ_REQ_PARAMETER_CLK_ADJ_SLOTS(buf)  buf[7] 
#define GET_LMP_CLK_ADJ_REQ_PARAMETER_CLK_ADJ_PERIOD(buf)  buf[8] 
/* LMP_PACKET_TYPE_TABLE_REQ */
#define GET_LMP_PACKET_TYPE_TABLE_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PACKET_TYPE_TABLE_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_PACKET_TYPE_TABLE_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_PACKET_TYPE_TABLE_REQ_PARAMETER_PACKET_TYPE_TABLE(buf)  buf[5] 
/* LMP_ESCO_LINK_REQ */
#define GET_LMP_ESCO_LINK_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_ESCO_LINK_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_ESCO_LINK_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_ESCO_HANDLE(buf)  buf[5] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_ESCO_LT_ADDR(buf)  buf[6] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_TIMING_CONTROL_FLAGS(buf)  buf[7] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_D_ESCO(buf)  buf[8] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_T_ESCO(buf)  buf[9] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_W_ESCO(buf)  buf[10] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_ESCO_PACKET_TYPE_C_P(buf)  buf[11] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_ESCO_PACKET_TYPE_P_C(buf)  buf[12] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_PACKET_LENGTH_C_P(buf)  ((uint16_t *)&buf[13]) 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_PACKET_LENGTH_P_C(buf)  ((uint16_t *)&buf[15]) 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_AIR_MODE(buf)  buf[17] 
#define GET_LMP_ESCO_LINK_REQ_PARAMETER_NEGOTIATION_STATE(buf)  buf[18] 
/* LMP_REMOVE_ESCO_LINK_REQ */
#define GET_LMP_REMOVE_ESCO_LINK_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_REMOVE_ESCO_LINK_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_REMOVE_ESCO_LINK_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_REMOVE_ESCO_LINK_REQ_PARAMETER_ESCO_HANDLE(buf)  buf[5] 
#define GET_LMP_REMOVE_ESCO_LINK_REQ_PARAMETER_ERROR_CODE(buf)  buf[6] 
/* LMP_CHANNEL_CLASSIFICATION_REQ */
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_PARAMETER_AFH_REPORTING_MODE(buf)  buf[5] 
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_PARAMETER_AFH_MIN_INTERVAL(buf)  ((uint16_t *)&buf[6]) 
#define GET_LMP_CHANNEL_CLASSIFICATION_REQ_PARAMETER_AFH_MAX_INTERVAL(buf)  ((uint16_t *)&buf[8]) 
/* LMP_CHANNEL_CLASSIFICATION */
#define GET_LMP_CHANNEL_CLASSIFICATION_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_CHANNEL_CLASSIFICATION_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_CHANNEL_CLASSIFICATION_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_CHANNEL_CLASSIFICATION_PARAMETER_AFH_CHANNEL_CLASSIFICATION(buf)  (buf[5])
/* LMP_SNIFF_SUBRATING_REQ */
#define GET_LMP_SNIFF_SUBRATING_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SNIFF_SUBRATING_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_SNIFF_SUBRATING_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_SNIFF_SUBRATING_REQ_PARAMETER_MAX_SNIFF_SUBRATE(buf)  buf[5] 
#define GET_LMP_SNIFF_SUBRATING_REQ_PARAMETER_MIN_SNIFF_MODE_TIEOUT(buf)  ((uint16_t *)&buf[6]) 
#define GET_LMP_SNIFF_SUBRATING_REQ_PARAMETER_SNIFF_SUBRATING_INSTANT(buf)  (uint32_t *)&buf[8] 
/* LMP_SNIFF_SUBRATING_RES */
#define GET_LMP_SNIFF_SUBRATING_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SNIFF_SUBRATING_RES_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_SNIFF_SUBRATING_RES_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_SNIFF_SUBRATING_RES_PARAMETER_MAX_SNIFF_SUBRATE(buf)  buf[5] 
#define GET_LMP_SNIFF_SUBRATING_RES_PARAMETER_MIN_SNIFF_MODE_TIMEOUT(buf)  ((uint16_t *)&buf[6]) 
#define GET_LMP_SNIFF_SUBRATING_RES_PARAMETER_SNIFF_SUBRATING_INSTANT(buf)  (uint32_t *)&buf[8] 
/* LMP_PAUSE_ENCRYPTION_REQ */
#define GET_LMP_PAUSE_ENCRYPTION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PAUSE_ENCRYPTION_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_PAUSE_ENCRYPTION_REQ_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_RESUME_ENCRYPTION_REQ */
#define GET_LMP_RESUME_ENCRYPTION_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_RESUME_ENCRYPTION_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_RESUME_ENCRYPTION_REQ_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_IO_CAPABILITY_REQ */
#define GET_LMP_IO_CAPABILITY_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_IO_CAPABILITY_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_IO_CAPABILITY_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_IO_CAPABILITY_REQ_PARAMETER_IO_CAPABILITIES(buf)  buf[5] 
#define GET_LMP_IO_CAPABILITY_REQ_PARAMETER_OOB_AUTH_DATA(buf)  buf[6] 
#define GET_LMP_IO_CAPABILITY_REQ_PARAMETER_AUTHENTICATION_REQUIREMENTS(buf)  buf[7] 
/* LMP_IO_CAPABILITY_RES */
#define GET_LMP_IO_CAPABILITY_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_IO_CAPABILITY_RES_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_IO_CAPABILITY_RES_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_IO_CAPABILITY_RES_PARAMETER_IO_CAPABILITIES(buf)  buf[5] 
#define GET_LMP_IO_CAPABILITY_RES_PARAMETER_OOB_AUTH_DATA(buf)  buf[6] 
#define GET_LMP_IO_CAPABILITY_RES_PARAMETER_AUTHENTICATION_REQUIREMENTS(buf)  buf[7] 
/* LMP_NUMERIC_COMPARISON_FAILED */
#define GET_LMP_NUMERIC_COMPARISON_FAILED_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_NUMERIC_COMPARISON_FAILED_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_NUMERIC_COMPARISON_FAILED_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_PASSKEY_FAILED */
#define GET_LMP_PASSKEY_FAILED_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PASSKEY_FAILED_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_PASSKEY_FAILED_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_OOB_FAILED */
#define GET_LMP_OOB_FAILED_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_OOB_FAILED_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_OOB_FAILED_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_KEYPRESS_NOTIFICATION */
#define GET_LMP_KEYPRESS_NOTIFICATION_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_KEYPRESS_NOTIFICATION_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_KEYPRESS_NOTIFICATION_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_KEYPRESS_NOTIFICATION_PARAMETER_NOTIFICATION_TYPE(buf)  buf[5] 
/* LMP_POWER_CONTROL_REQ */
#define GET_LMP_POWER_CONTROL_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_POWER_CONTROL_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_POWER_CONTROL_REQ_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_POWER_CONTROL_REQ_PARAMETER_POWER_ADJ_REQ(buf)  buf[5] 
/* LMP_POWER_CONTROL_RES */
#define GET_LMP_POWER_CONTROL_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_POWER_CONTROL_RES_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_POWER_CONTROL_RES_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_POWER_CONTROL_RES_PARAMETER_POWER_ADJ_RSP(buf)  buf[5] 
/* LMP_PING_REQ */
#define GET_LMP_PING_REQ_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PING_REQ_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_PING_REQ_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_PING_RES */
#define GET_LMP_PING_RES_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_PING_RES_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_PING_RES_EXTENDED_OPCODE(buf)  (buf[4])
/* LMP_SAM_SET_TYPE0 */
#define GET_LMP_SAM_SET_TYPE0_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SAM_SET_TYPE0_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_SAM_SET_TYPE0_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_SAM_SET_TYPE0_PARAMETER_UPDATE_MODE(buf)  buf[5] 
#define GET_LMP_SAM_SET_TYPE0_PARAMETER_SAM_TYPE0_SUBMAP(buf)  (buf[6])
/* LMP_SAM_DEFINE_MAP */
#define GET_LMP_SAM_DEFINE_MAP_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SAM_DEFINE_MAP_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_SAM_DEFINE_MAP_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_SAM_DEFINE_MAP_PARAMETER_SAM_INDEX(buf)  buf[5] 
#define GET_LMP_SAM_DEFINE_MAP_PARAMETER_T_SAM_SM(buf)  buf[6] 
#define GET_LMP_SAM_DEFINE_MAP_PARAMETER_N_SAM_SM(buf)  buf[7] 
#define GET_LMP_SAM_DEFINE_MAP_PARAMETER_SAM_SUBMAPS(buf)  (buf[8])
/* LMP_SAM_SWITCH */
#define GET_LMP_SAM_SWITCH_TID(buf) ((buf[3] & (BIT(7)))>>7)
#define GET_LMP_SAM_SWITCH_OPCODE(buf)  (buf[3]) & ~(BIT(7))
#define GET_LMP_SAM_SWITCH_EXTENDED_OPCODE(buf)  (buf[4])
#define GET_LMP_SAM_SWITCH_PARAMETER_SAM_INDEX(buf)  buf[5] 
#define GET_LMP_SAM_SWITCH_PARAMETER_TIMING_CONTROL_FLAGS(buf)  buf[6] 
#define GET_LMP_SAM_SWITCH_PARAMETER_D_SAM(buf)  buf[7] 
#define GET_LMP_SAM_SWITCH_PARAMETER_SAM_INSTANT(buf)  (uint32_t *)&buf[8] 
#endif