/*******************************************************************************
 * @file  btc_hci.h
 * @brief
 *******************************************************************************
 * # License
 * <b>Copyright 2024 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#ifndef _BTC_HCI_H_
#define _BTC_HCI_H_

#include "btc_dev.h"

typedef struct hci_inq_event_params_s
{
  uint8_t rssi;
  uint8_t bd_addr[MAC_ADDR_LEN];
  uint8_t psr_mode;
  uint8_t class_of_device[CLASS_OF_DEV_LEN];
  uint8_t *eir_buf;
  uint8_t eir_len;
  uint8_t clock_offset;
} hci_inq_event_params_t;


#define HCI_EVENT_MAP_MASK        0xFFFFFFFF
#define HCI_MAX_CMD_PKT_LENGTH    256
#define HCI_MAX_STATUS_EVT_LENGTH 2
#define MAX_HCI_EVENT_PKT_LENGTH  255 //TODO check it in standard and change it accordingly
#define NEW_SYNC_CONN 1
#define UPDATE_SYNC_CONN 2

#define SCO_HV1 BIT(0)
#define SCO_HV2 BIT(1)
#define SCO_HV3 BIT(2)
#define ESCO_EV3 BIT(3)
#define ESCO_EV4 BIT(4)
#define ESCO_EV5 BIT(5)
#define ESCO_2EV3 BIT(6)
#define ESCO_3EV3 BIT(7)
#define ESCO_2EV5 BIT(8)
#define ESCO_3EV5 BIT(9)
#define ADD_SCO_HV1 0x0020
#define ADD_SCO_HV2 0x0040
#define ADD_SCO_HV3 0x0080

/* Packet boundary flags for HCI data packets */
#define CONTINUATION_FRAG_PB 1
#define FIRST_PKT_PB 2

#define READ_CURRENT_TX_PWR_LEVEL 0x0
#define READ_MAX_POWER_LEVEL 0x1

#define SCO_CONN_HANDLE_TO_SCO_HANDLE(x) ((x & 0x20) >> 5)
#define ESCO_CONN_HANDLE_TO_ESCO_HANDLE(x) ((x & 0x40) >> 6)
#define BREDR_SCO_PEER_ID_TO_CONN_HANDLE(x, y) \
  (x ? x : 8) | SCO_LT | (y << 5) // y is 1 most of the times. 1 implies sco_handle in slave_info
#define BREDR_ESCO_PEER_ID_TO_CONN_HANDLE(x, y) \
  (x ? x : 8) | ESCO_LT | (y << 6) // y is 1 most of the times. 1 implies esco_handle in slave_info

/* HCI Stored Link Key Delete Flag */
#define HCI_DEL_STORED_LINK_KEY_SP_BD_ADDR 0x00
#define HCI_DEL_STORED_LINK_KEY_FOR_ALL_BD_ADDR 0x01

/* HCI Read Stored Link Key Flags*/
#define HCI_READ_STORED_LINK_KEY_SP_BD_ADDR 0x00
#define HCI_READ_STORED_LINK_KEY_FOR_ALL_BD_ADDR 0x01

/* HCI Event Filter types */
#define HCI_CLEAR_ALL_EVENT_FLT_TYPE 0x00
#define HCI_INQ_EVENT_FLT_TYPE 0x01
#define HCI_CONN_EVENT_FLT_TYPE 0x02

/* HCI Event Filter Condition Types */
#define HCI_CLEAR_ALL_EVENT_FLT_COND 0x00

/* HCI Inquiry Event Condition Types */
#define HCI_INQ_ALL_RESP_COND_TYPE 0x00
#define HCI_INQ_SP_CLASS_OF_DEVICE 0x01
#define HCI_INQ_SP_BD_ADDR 0x02

/* HCI Connection Event Condition Types */
#define HCI_CONN_ALLOW_ALL_CONN 0x00
#define HCI_CONN_SP_CLASS_OF_DEVICE 0x01
#define HCI_CONN_SP_BD_ADDR 0x02

/* HCI Event Auto Accept Flag */
#define HCI_AUTO_ACPT_OFF 0x01
#define HCI_AUTO_ACPT_ON_DIS_SWCH_ROLE 0x02
#define HCI_AUTO_ACPT_ON_SWCH_ROLE 0x03

/* BT ERROR Codes */
#define BT_UNKNOWN_STATUS 0xFF
#define BT_SUCCESS_STATUS 0x00
#define UNKNOWN_HCI_COMMAND 0X01
#define UNKNOWN_CONNECTION_IDENTIFIER 0X02
#define HARDWARE_FAILURE 0X03
#define PAGE_TIMEOUT 0X04
#define AUTHENTICATION_FAILURE 0X05
#define PIN_OR_KEY_MISSING 0X06
#define MEMORY_CAPACITY_EXCEEDED 0X07
#define CONNECTION_TIMEOUT 0X08
#define CONNECTION_LIMIT_EXCEEDED 0X09
#define SYNC_CONN_LIMIT_TO_A_DEVICE_EXCEEDED 0X0A
#define ACL_CONNECTION_ALREADY_EXISTS 0X0B
#define COMMAND_DISALLOWED 0X0C
#define CONN_REJECTED_DUE_TO_LIMITED_RESOURCES 0X0D
#define CONN_REJECTED_DUE_TO_SECURITY_REASONS 0X0E
#define CONN_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDR 0X0F
#define CONN_ACCEPT_TIMEOUT_EXCEEDED 0X10
#define UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE 0X11
#define INVALID_HCI_COMMAND_PARAMETERS 0X12
#define REM_USER_TERMINATED_CONNECTION 0X13
#define REM_DEV_TERMINATED_CONN_DUE_TO_LOW_RESOURCES 0X14
#define REM_DEV_TERMINATED_CONN_DUE_TO_POWER_OFF 0X15
#define CONNECTION_TERMINATED_BY_LOCAL_HOST 0X16
#define REPEATED_ATTEMPTS 0X17
#define PAIRING_NOT_ALLOWED 0X18
#define UNKNOWN_LMP_PDU 0X19
#define UNSUP_REM_FEATURE_OR_UNSUP_LMP_FEATURE 0X1A
#define SCO_OFFSET_REJECTED 0X1B
#define SCO_INTERVAL_REJECTED 0X1C
#define SCO_AIR_MODE_REJECTED 0X1D
#define INVALID_LMP_PARAMETERS 0X1E
#define UNSPECIFIED_ERROR 0X1F
#define UNSUPPORTED_LMP_PARAMETER_VALUE 0X20
#define ROLE_CHANGE_NOT_ALLOWED 0X21
#define LMP_RESPONSE_TIMEOUT_OR_LL_RESPONSE_TIMEOUT 0X22
#define LMP_ERROR_TRANSACTION_COLLISION 0X23
#define LMP_PDU_NOT_ALLOWED 0X24
#define ENCRYPTION_MODE_NOT_ACCEPTABLE 0X25
#define LINK_KEY_CANNOT_BE_CHANGED 0X26
#define REQUESTED_QOS_NOT_SUPPORTED 0X27
#define INSTANT_PASSED 0X28
#define PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED 0X29
#define DIFFERENT_TRANSACTION_COLLISION 0X2A
#define QOS_UNACCEPTABLE_PARAMETER 0X2C
#define QOS_REJECTED 0X2D
#define CHANNEL_ASSESSMENT_NOT_SUPPORTED 0X2E
#define INSUFFICIENT_SECURITY 0X2F
#define PARAMETER_OUT_OF_MANDATORY_RANGE 0X30
#define ROLE_SWITCH_PENDING 0X32
#define RESERVED_SLOT_VIOLATION 0X34
#define ROLE_SWITCH_FAILED 0X35
#define EXTENDED_INQUIRY_RESPONSE_TOO_LARGE 0X36
#define SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST 0X37
#define HOST_BUSY_PAIRING 0X38
#define CONN_REJECTED_DUE_TO_NO_SUITABLE_CHANN_FOUND 0X39
#define CONTROLLER_BUSY 0X3A
#define UNACCEPTABLE_CONNECTION_INTERVAL 0X3B
#define DIRECTED_ADVERTISING_TIMEOUT 0X3C
#define CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE 0X3D
#define CONNECTION_FAILED_TO_BE_ESTABLISHED 0X3E
#define MAC_CONNECTION_FAILED 0X3F

#define UNKNOWN_ADVERTISING_IDENTIFIER 0x42 // AE_ENABLE
#define LIMIT_REACHED 0x43
#define DISCONNECTION_FROM_RE_CONNECTION 0xFF

// #define BIT(x) ((uint32_t)1 << (x))

#define INQ_COMPLETE_EVENT BIT(0)
#define INQ_RESULT_EVENT BIT(1)
#define CONN_COMPLETE_EVENT BIT(2)
#define CONN_REQ_EVENT BIT(3)
#define DISCONN_COMPLETE_EVENT BIT(4)
#define AUTH_COMPLETE_EVENT BIT(5)
#define REMOTE_NAME_REQ_COMPLETE_EVENT BIT(6)
#define ENCRYPT_CHANGE_EVENT BIT(7)

#define CHANGE_CONN_LINK_KEY_COMPLETE_EVENT BIT(0)
#define MASTER_LINK_KEY_COMPLETE_EVENT BIT(1)
#define READ_REMOTE_SUPPORTED_FEAURES_COMPLETE_EVENT BIT(2)
#define READ_REMOTE_VERSION_INFO_COMPLETE_EVENT BIT(3)
#define QOS_SETUP_COMPLETE_EVENT BIT(4)

#define HARDWARE_ERROR_EVENT BIT(7)

#define FLUSH_OCCURED_EVENT BIT(0)
#define ROLE_CHANGE_EVENT BIT(1)

#define MODE_CHANGE_EVENT BIT(3)
#define RETURN_LINK_KEYS_EVENT BIT(4)
#define PIN_CODE_REQUEST_EVENT BIT(5)
#define LINK_KEY_REQ_EVENT BIT(6)
#define LINK_KEY_NOTIFICATION_EVENT BIT(7)

#define LOOPBACK_COMMNAD_EVENT BIT(0)
#define DATA_BUFFER_OVERFLOW_EVENT BIT(1)
#define MAX_SLOT_CHANGE_EVENT BIT(2)
#define READ_CLK_OFFSET_COMPLETE_EVENT BIT(3)
#define CONN_PKT_TYPE_CHANGED_EVENT BIT(4)
#define QOS_VIOLATION_EVENT BIT(5)
#define PAGE_SCAN_MODE_CHANGE_EVENT BIT(6)
#define PAGE_SCAN_REPETITION_MODE_CHANGE_EVENT BIT(7)

#define FLOW_SPECIFICATION_COMPLETE_EVENT BIT(0)
#define INQ_RESULT_WITH_RSSI_EVENT BIT(1)
#define READ_REMOTE_EXT_FEATURES_COMPLETE_EVENT BIT(2)

#define SYNC_CONN_COMPLETE_EVENT BIT(3)
#define SYNC_CONN_CHANGED_EVENT BIT(4)
#define SNIFF_SUBRATING_EVENT BIT(5)
#define EXT_INQ_RESULT_EVENT BIT(6)
#define ENC_KEY_REFRESH_COMPLETE_EVENT BIT(7)
#define IO_CAPABILITY_REQ_EVENT BIT(0)
#define IO_CAPABILITY_REQ_REPLY_EVENT BIT(1)
#define USER_CONFIRM_REQ_EVENT BIT(2)
#define USER_PASSKEY_REQ_EVENT BIT(3)
#define REMOTE_OOB_DATA_REQ_EVENT BIT(4)
#define SIMPLE_PAIRING_COMPLETE_EVENT BIT(5)

#define LINK_SUPERVISION_TIMEOUT_CHANGED_EVENT BIT(7)
#define ENHANCED_FLUSH_COMPLETE_EVENT BIT(0)

#define USER_PASSKEY_NOTIFICATION_EVENT BIT(2)
#define KEYPRESS_NOTIFICATION_EVENT BIT(3)
#define REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION_EVENT BIT(4)
#define LE_META_EVENT BIT(5)

/* Defines */

#define MAC_ADDR_LEN 6
#define DEFAULT_MAX_NUM_OF_STORED_LINK_KEY 7

#define FEATURE_MASK_LENGTH 8
#define EXT_FEATURE_MASK_LENGTH 8
#define DEFAULT_CLOCK_DRIFT 250
#define DEFAULT_CLOCK_JITTER 10
#define DEFAULT_LINK_SUPERVISION_TIMEOUT 0x2580 // In number of slots = 6Seconds
#define MAX_NUM_SUPPORTED_FEATURE_PAGE 2
#define MAX_EVENT_MASK_LENGTH 8
#define DEFAULT_ACL_PACKET_LENGTH 17
#define MAX_ACL_PACKET_LENGTH 1021
#define MAX_SCO_PACKET_LENGTH 30
#define MAX_SCO_PACKET_LENGTH_RAM 64
#define CLASS_OF_DEV_LEN 3
#define HCI_CMD_MAP_LENGTH 64
#define BT_RX_MAX_PKT_LEN 1028
#define BT_TX_MAX_PKT_LEN 1025
#define BT_LC_HEAD_ROOM 4
#define LINK_KEY_LEN 16
#define ENC_KEY_KC_MAX_LEN 16
#define ENC_KEY_KC_MIN_LEN 7
#define RAND_NUM_SIZE 16
#define MAX_PIN_CODE_LEN 16
#define PUBLIC_KEY_LEN 48
#define PUBLIC_KEY_LEN_256 64
#define SIZE_OF_C_VAL 16
#define SIZE_OF_DHKEY 16
#define SIZE_OF_CONFIRMATION_VAL 16
#define MAX_PRIVATE_KEY_LEN 24
#define NUM_OF_DWORDS_IN_G 6
#define PRIVATE_KEY_LEN 24
#define LEN_OF_GX 24
#define LEN_OF_GY 24
#define NUM_OF_DWORDS_IN_B 6
#define NUM_OF_DWORDS_IN_A 6
#define SIZE_OF_R1 24
#define NUM_OF_DWORDS_IN_P 6
#define NUM_DWORDS_IN_PUBLIC_KEY 12
#define NUM_DWORDS_IN_PRIVATE_KEY 6
#define SIZE_OF_R 16
#define DHKEY_LEN 24
#define SIZE_OF_KEY_ID 4
#define SIZE_OF_SCALAR 24

#define BT_STATUS_SUCCESS 0
#define BT_STATUS_FAILURE 1
#define BT_NODE_NOT_FOUND 0xFF
#define BT_NODE_FOUND 0x00

#define ACCEPT_PARAMS_SET BIT(0)
#define REJECT_PARAMS_SET BIT(1)
#define SEND_ANOTHER_PARAMS_SET BIT(2)

#define EVENT_COMPLETED 0
#define EVENT_PENDING 1

#define BT_HOST_RX_QUEUE_NUM 7
#define BT_HOST_RX_BER_QUEUE_NUM 6
#define BT_HOST_RX_QUEUE_NUM_OFFSET 12

#define PAGE_SCAN_MODE_R0 0
#define PAGE_SCAN_MODE_R1 1
#define PAGE_SCAN_MODE_R2 2

#define HCI_CMD_NOT_IMPLEMENTED 1

/* HCI Event codes */
#define HCI_INQUIRY_COMPLETE_EVENT 0x01
#define HCI_INQUIRY_RESULT_EVENT 0x02
#define HCI_CONN_COMPLETE_EVENT 0x03
#define HCI_CONN_REQUEST_EVENT 0x04
#define HCI_DISCONNECTION_COMPLETE_EVENT 0x05
#define HCI_AUTHENTICATION_COMPLETE_EVENT 0x06
#define HCI_REMOTE_NAME_REQUEST_COMPLETE_EVENT 0x07
#define HCI_ENCRYPTION_CHANGE_EVENT 0x08
#define HCI_CHANGE_CONNECTION_LINK_KEY_COMPLETE_EVENT 0x09
#define HCI_MASTER_LINK_KEY_COMPLETE_EVENT 0x0A
#define HCI_READ_REMOTE_SUPP_FTRS_EVENT 0x0B
#define HCI_READ_REMOTE_VERS_INFO_EVENT 0x0C
#define HCI_QOS_SETUP_COMPLETE_EVENT 0x0D
#define HCI_CMD_COMPLETE_EVENT 0x0E
#define HCI_CMD_STATUS_EVENT 0x0F
#define HCI_HARDWARE_ERROR_EVENT 0x10
#define HCI_FLUSH_OCCURRED_EVENT 0x11
#define HCI_ROLE_CHANGE_EVENT 0x12
#define HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT 0x13
#define HCI_MODE_CHANGE_EVENT 0x14
#define HCI_RETURN_LINK_KEYS_EVENT 0x15
#define HCI_PIN_CODE_REQUEST_EVENT 0x16
#define HCI_LINK_KEY_REQUEST_EVENT 0x17
#define HCI_LINK_KEY_NOTIFICATION_EVENT 0x18
#define HCI_LOOPBACK_COMMAND_EVENT 0x19
#define HCI_DATA_BUFFER_OVERFLOW_EVENT 0x1A
#define HCI_MAX_SLOTS_CHANGE_EVENT 0x1B
#define HCI_READ_CLOCK_OFFSET_COMPLETE_EVENT 0x1C
#define HCI_CONNECTION_PACKET_TYPE_CHANGED_EVENT 0x1D
#define HCI_QOS_VIOLATION_EVENT 0x1E
#define HCI_PAGE_SCAN_REPETITION_MODE_CHANGE_EVENT 0x20
#define HCI_FLOW_SPECIFICATION_COMPLETE_EVENT 0x21
#define HCI_INQUIRY_RESULT_WITH_RSSI_EVENT 0x22
#define HCI_READ_REM_EXTD_FEATURES_COMPLETE_EVENT 0x23
#define HCI_SYNCHRONOUS_CONNECTION_COMPLETE_EVENT 0x2C
#define HCI_SYNCHRONOUS_CONNECTION_CHANGED_EVENT 0x2D
#define HCI_SNIFF_SUBRATING_EVENT 0x2E
#define HCI_EXTENDED_INQUIRY_RESULT_EVENT 0x2F
#define HCI_ENCRYPTION_KEY_REFRESH_COMPLETE_EVENT 0x30
#define HCI_IO_CAPABILITY_REQUEST_EVENT 0x31
#define HCI_IO_CAPABILITY_RESPONSE_EVENT 0x32
#define HCI_USER_CONFIRMATION_REQUEST_EVENT 0x33
#define HCI_USER_PASSKEY_REQUEST_EVENT 0x34
#define HCI_REMOTE_OOB_DATA_REQUEST_EVENT 0x35
#define HCI_SIMPLE_PAIRING_COMPLETE_EVENT 0x36
#define HCI_LINK_SUPERVISION_TIMEOUT_CHANGED_EVENT 0x38
#define HCI_ENHANCED_FLUSH_COMPLETE_EVENT 0x39
#define HCI_USER_PASSKEY_NOTIFICATION_EVENT 0x3B
#define HCI_KEYPRESS_NOTIFICATION_EVENT 0x3C
#define HCI_REM_HOST_SUPP_FEATURES_NOTIFICATION_EVENT 0x3D
#define HCI_LE_META_EVENT 0x3E
#define HCI_PHYSICAL_LINK_COMPLETE_EVENT 0x40
#define HCI_CHANNEL_SELECTED_EVENT 0x41
#define HCI_DISCONNECTION_PHYSICAL_LINK_COMPLETE_EVENT 0x42
#define HCI_PHYSICAL_LINK_LOSS_EARLY_WARNING_EVENT 0x43
#define HCI_PHYSICAL_LINK_RECOVERY_EVENT 0x44
#define HCI_LOGICAL_LINK_COMPLETE_EVENT 0x45
#define HCI_DISCONNECTION_LOGICAL_LINK_COMPLETE_EVENT 0x46
#define HCI_FLOW_SPEC_MODIFY_COMPLETE_EVENT 0x47
#define HCI_NUMBER_OF_COMPLETED_DATA_BLOCKS_EVENT 0x48
#define HCI_AMP_START_TEST_EVENT 0x49
#define HCI_AMP_TEST_END_EVENT 0x4A
#define HCI_AMP_RECEIVER_REPORT_EVENT 0x4B
#define HCI_SHORT_RANGE_MODE_CHANGE_COMPLETE_EVENT 0x4C
#define HCI_AMP_STATUS_CHANGE_EVENT 0x4D
#define HCI_AUTHENTICATED_PAYLOAD_TIMEOUT_EVENT 0x57
#define HCI_VENDOR_SPECIFIC_EVENT 0xFF

/* HCI Vendor specific sub event Event codes */
#define HCI_VENDOR_SPECIFIC_SUBEVENT_UT_POWER_CONTROL_EVENT 0xFE

#define HCI_VIRTUAL_DISCONNECTION_COMPLETE_EVENT 0xFD
#define HCI_VIRTUAL_CONN_COMPLETE_EVENT 0xFC

#endif
