#Macros for command parameters in testcases

META_DATA = [0x00, 0x00, 0x01, 0x00]
DATA = [0x00]
INQUIRY_SCAN_ACTIVITY = 0x1000
INQUIRY_SCAN_WINDOW = 0x0012
LAP = [0x03, 0x8b, 0x9e]
INQUIRY_LENGTH = 4
NUM_RESPONSES = 4
PAGE_SCAN_REP_MODE = 0
RESERVED = 0
CLK_OFFSET = 0
SCAN_ENABLE = 1
MAX_PERIOD_LENGTH = 12
MIN_PERIOD_LENGTH = 5
PKT_TYPE = 0
ALLOW_ROLE_SWITCH = 0
DISABLE_SIMPLE_SECURE_PAIRING = 0
HCI_DEL_STORED_LINK_KEY_FOR_ALL_BD_ADDR = 1

"""
Bluetooth Error Codes converted from C macros to Python constants
"""

# BT ERROR Codes
INVALID_CONN_HANDLE = 0xFF
BT_UNKNOWN_STATUS = 0xFF
BT_SUCCESS_STATUS = 0x00
UNKNOWN_HCI_COMMAND = 0x01
UNKNOWN_CONNECTION_IDENTIFIER = 0x02
HARDWARE_FAILURE = 0x03
PAGE_TIMEOUT = 0x04
AUTHENTICATION_FAILURE = 0x05
PIN_OR_KEY_MISSING = 0x06
MEMORY_CAPACITY_EXCEEDED = 0x07
CONNECTION_TIMEOUT = 0x08
CONNECTION_LIMIT_EXCEEDED = 0x09
SYNC_CONN_LIMIT_TO_A_DEVICE_EXCEEDED = 0x0A
ACL_CONNECTION_ALREADY_EXISTS = 0x0B
COMMAND_DISALLOWED = 0x0C
CONN_REJECTED_DUE_TO_LIMITED_RESOURCES = 0x0D
CONN_REJECTED_DUE_TO_SECURITY_REASONS = 0x0E
CONN_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDR = 0x0F
CONN_ACCEPT_TIMEOUT_EXCEEDED = 0x10
UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE = 0x11
INVALID_HCI_COMMAND_PARAMETERS = 0x12
REM_USER_TERMINATED_CONNECTION = 0x13
REM_DEV_TERMINATED_CONN_DUE_TO_LOW_RESOURCES = 0x14
REM_DEV_TERMINATED_CONN_DUE_TO_POWER_OFF = 0x15
CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x16
REPEATED_ATTEMPTS = 0x17
PAIRING_NOT_ALLOWED = 0x18
UNKNOWN_LMP_PDU = 0x19
UNSUP_REM_FEATURE_OR_UNSUP_LMP_FEATURE = 0x1A
SCO_OFFSET_REJECTED = 0x1B
SCO_INTERVAL_REJECTED = 0x1C
SCO_AIR_MODE_REJECTED = 0x1D
INVALID_LMP_PARAMETERS = 0x1E
UNSPECIFIED_ERROR = 0x1F
UNSUPPORTED_LMP_PARAMETER_VALUE = 0x20
ROLE_CHANGE_NOT_ALLOWED = 0x21
LMP_RESPONSE_TIMEOUT_OR_LL_RESPONSE_TIMEOUT = 0x22
LMP_ERROR_TRANSACTION_COLLISION = 0x23
LMP_PDU_NOT_ALLOWED = 0x24
ENCRYPTION_MODE_NOT_ACCEPTABLE = 0x25
LINK_KEY_CANNOT_BE_CHANGED = 0x26
REQUESTED_QOS_NOT_SUPPORTED = 0x27
INSTANT_PASSED = 0x28
PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED = 0x29
DIFFERENT_TRANSACTION_COLLISION = 0x2A
QOS_UNACCEPTABLE_PARAMETER = 0x2C
QOS_REJECTED = 0x2D
CHANNEL_ASSESSMENT_NOT_SUPPORTED = 0x2E
INSUFFICIENT_SECURITY = 0x2F
PARAMETER_OUT_OF_MANDATORY_RANGE = 0x30
ROLE_SWITCH_PENDING = 0x32
RESERVED_SLOT_VIOLATION = 0x34
ROLE_SWITCH_FAILED = 0x35
EXTENDED_INQUIRY_RESPONSE_TOO_LARGE = 0x36
SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST = 0x37
HOST_BUSY_PAIRING = 0x38
CONN_REJECTED_DUE_TO_NO_SUITABLE_CHANN_FOUND = 0x39
CONTROLLER_BUSY = 0x3A
UNACCEPTABLE_CONNECTION_INTERVAL = 0x3B
DIRECTED_ADVERTISING_TIMEOUT = 0x3C
CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE = 0x3D
CONNECTION_FAILED_TO_BE_ESTABLISHED = 0x3E
MAC_CONNECTION_FAILED = 0x3F

UNKNOWN_ADVERTISING_IDENTIFIER = 0x42  # AE_ENABLE
LIMIT_REACHED = 0x43
DISCONNECTION_FROM_RE_CONNECTION = 0xFF