"""
LPW to ULC Notification Events
"""
PAGE_SUCCESS_NOTIFICATION_FROM_LPW = 0x01
PAGE_SCAN_SUCCESS_NOTIFICATION_FROM_LPW = 0x02
INQUIRY_COMPLETE_INDICATION_FROM_LPW = 0x03
CONNECTION_COMPLETE_NOTIFICATION_FROM_LPW = 0x04
POWER_CONTROL_NOTIFICATION_FROM_LPW = 0x05
DISCONNECTION_COMPLETE_NOTIFICATION_FROM_LPW = 0x06

'''Inquiry Modes'''
INQUIRY_RESULT = 0
INQUIRY_RESULT_WITH_RSSI = 1
INQUIRY_RESULT_EXTENDED = 2